-- generated via some magic and Vim's :digraphs command

return {
  ["NU"]  = {"0", "0", "0", "a"}, -- LINE FEED
  ["SH"]  = {"0", "0", "0", "1"}, -- START OF HEADING
  ["SX"]  = {"0", "0", "0", "2"}, -- START OF TEXT
  ["EX"]  = {"0", "0", "0", "3"}, -- END OF TEXT
  ["ET"]  = {"0", "0", "0", "4"}, -- END OF TRANSMISSION
  ["EQ"]  = {"0", "0", "0", "5"}, -- ENQUIRY
  ["AK"]  = {"0", "0", "0", "6"}, -- ACKNOWLEDGE
  ["BL"]  = {"0", "0", "0", "7"}, -- ALERT
  ["BS"]  = {"0", "0", "0", "8"}, -- BACKSPACE
  ["HT"]  = {"0", "0", "0", "9"}, -- CHARACTER TABULATION
  ["LF"]  = {"0", "0", "0", "a"}, -- LINE FEED
  ["VT"]  = {"0", "0", "0", "b"}, -- LINE TABULATION
  ["FF"]  = {"0", "0", "0", "c"}, -- FORM FEED
  ["CR"]  = {"0", "0", "0", "d"}, -- CARRIAGE RETURN
  ["SO"]  = {"0", "0", "0", "e"}, -- SHIFT OUT
  ["SI"]  = {"0", "0", "0", "f"}, -- SHIFT IN
  ["DL"]  = {"0", "0", "1", "0"}, -- DATA LINK ESCAPE
  ["D1"]  = {"0", "0", "1", "1"}, -- DEVICE CONTROL ONE
  ["D2"]  = {"0", "0", "1", "2"}, -- DEVICE CONTROL TWO
  ["D3"]  = {"0", "0", "1", "3"}, -- DEVICE CONTROL THREE
  ["D4"]  = {"0", "0", "1", "4"}, -- DEVICE CONTROL FOUR
  ["NK"]  = {"0", "0", "1", "5"}, -- NEGATIVE ACKNOWLEDGE
  ["SY"]  = {"0", "0", "1", "6"}, -- SYNCHRONOUS IDLE
  ["EB"]  = {"0", "0", "1", "7"}, -- END OF TRANSMISSION BLOCK
  ["CN"]  = {"0", "0", "1", "8"}, -- CANCEL
  ["EM"]  = {"0", "0", "1", "9"}, -- END OF MEDIUM
  ["SB"]  = {"0", "0", "1", "a"}, -- SUBSTITUTE
  ["EC"]  = {"0", "0", "1", "b"}, -- ESCAPE
  ["FS"]  = {"0", "0", "1", "c"}, -- INFORMATION SEPARATOR FOUR
  ["GS"]  = {"0", "0", "1", "d"}, -- INFORMATION SEPARATOR THREE
  ["RS"]  = {"0", "0", "1", "e"}, -- INFORMATION SEPARATOR TWO
  ["US"]  = {"0", "0", "1", "f"}, -- INFORMATION SEPARATOR ONE
  ["SP"]  = {"0", "0", "2", "0"}, -- SPACE
  ["Nb"]  = {"0", "0", "2", "3"}, -- NUMBER SIGN
  ["DO"]  = {"0", "0", "2", "4"}, -- DOLLAR SIGN
  ["At"]  = {"0", "0", "4", "0"}, -- COMMERCIAL AT
  ["<("]  = {"0", "0", "5", "b"}, -- LEFT SQUARE BRACKET
  ["//"]  = {"0", "0", "5", "c"}, -- REVERSE SOLIDUS
  [")>"]  = {"0", "0", "5", "d"}, -- RIGHT SQUARE BRACKET
  ["'>"]  = {"0", "0", "5", "e"}, -- CIRCUMFLEX ACCENT
  ["'!"]  = {"0", "0", "6", "0"}, -- GRAVE ACCENT
  ["(!"]  = {"0", "0", "7", "b"}, -- LEFT CURLY BRACKET
  ["!!"]  = {"0", "0", "7", "c"}, -- VERTICAL LINE
  ["!)"]  = {"0", "0", "7", "d"}, -- RIGHT CURLY BRACKET
  ["'?"]  = {"0", "0", "7", "e"}, -- TILDE
  ["DT"]  = {"0", "0", "7", "f"}, -- DELETE
  ["PA"]  = {"0", "0", "8", "0"}, -- PADDING CHARACTER
  ["HO"]  = {"0", "0", "8", "1"}, -- HIGH OCTET PRESET
  ["BH"]  = {"0", "0", "8", "2"}, -- BREAK PERMITTED HERE
  ["NH"]  = {"0", "0", "8", "3"}, -- NO BREAK HERE
  ["IN"]  = {"0", "0", "8", "4"}, -- INDEX
  ["NL"]  = {"0", "0", "8", "5"}, -- NEXT LINE
  ["SA"]  = {"0", "0", "8", "6"}, -- START OF SELECTED AREA
  ["ES"]  = {"0", "0", "8", "7"}, -- END OF SELECTED AREA
  ["HS"]  = {"0", "0", "8", "8"}, -- CHARACTER TABULATION SET
  ["HJ"]  = {"0", "0", "8", "9"}, -- CHARACTER TABULATION WITH JUSTIFICATION
  ["VS"]  = {"0", "0", "8", "a"}, -- LINE TABULATION SET
  ["PD"]  = {"0", "0", "8", "b"}, -- PARTIAL LINE FORWARD
  ["PU"]  = {"0", "0", "8", "c"}, -- PARTIAL LINE BACKWARD
  ["RI"]  = {"0", "0", "8", "d"}, -- REVERSE LINE FEED
  ["S2"]  = {"0", "0", "8", "e"}, -- SINGLE SHIFT TWO
  ["S3"]  = {"0", "0", "8", "f"}, -- SINGLE SHIFT THREE
  ["DC"]  = {"0", "0", "9", "0"}, -- DEVICE CONTROL STRING
  ["P1"]  = {"0", "0", "9", "1"}, -- PRIVATE USE ONE
  ["P2"]  = {"0", "0", "9", "2"}, -- PRIVATE USE TWO
  ["TS"]  = {"0", "0", "9", "3"}, -- SET TRANSMIT STATE
  ["CC"]  = {"0", "0", "9", "4"}, -- CANCEL CHARACTER
  ["MW"]  = {"0", "0", "9", "5"}, -- MESSAGE WAITING
  ["SG"]  = {"0", "0", "9", "6"}, -- START OF GUARDED AREA
  ["EG"]  = {"0", "0", "9", "7"}, -- END OF GUARDED AREA
  ["SS"]  = {"0", "0", "9", "8"}, -- START OF STRING
  ["GC"]  = {"0", "0", "9", "9"}, -- SINGLE GRAPHIC CHARACTER INTRODUCER
  ["SC"]  = {"0", "0", "9", "a"}, -- SINGLE CHARACTER INTRODUCER
  ["CI"]  = {"0", "0", "9", "b"}, -- CONTROL SEQUENCE INTRODUCER
  ["ST"]  = {"0", "0", "9", "c"}, -- STRING TERMINATOR
  ["OC"]  = {"0", "0", "9", "d"}, -- OPERATING SYSTEM COMMAND
  ["PM"]  = {"0", "0", "9", "e"}, -- PRIVACY MESSAGE
  ["AC"]  = {"0", "0", "9", "f"}, -- APPLICATION PROGRAM COMMAND
  ["NS"]  = {"0", "0", "a", "0"}, -- NO-BREAK SPACE
  ["!I"]  = {"0", "0", "a", "1"}, -- INVERTED EXCLAMATION MARK
  ["Ct"]  = {"0", "0", "a", "2"}, -- CENT SIGN
  ["Pd"]  = {"0", "0", "a", "3"}, -- POUND SIGN
  ["Cu"]  = {"0", "0", "a", "4"}, -- CURRENCY SIGN
  ["Ye"]  = {"0", "0", "a", "5"}, -- YEN SIGN
  ["BB"]  = {"0", "0", "a", "6"}, -- BROKEN BAR
  ["SE"]  = {"0", "0", "a", "7"}, -- SECTION SIGN
  ["':"]  = {"0", "0", "a", "8"}, -- DIAERESIS
  ["Co"]  = {"0", "0", "a", "9"}, -- COPYRIGHT SIGN
  ["-a"]  = {"0", "0", "a", "a"}, -- FEMININE ORDINAL INDICATOR
  ["<<"]  = {"0", "0", "a", "b"}, -- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
  ["NO"]  = {"0", "0", "a", "c"}, -- NOT SIGN
  ["--"]  = {"0", "0", "a", "d"}, -- SOFT HYPHEN
  ["Rg"]  = {"0", "0", "a", "e"}, -- REGISTERED SIGN
  ["'m"]  = {"0", "0", "a", "f"}, -- MACRON
  ["DG"]  = {"0", "0", "b", "0"}, -- DEGREE SIGN
  ["+-"]  = {"0", "0", "b", "1"}, -- PLUS-MINUS SIGN
  ["2S"]  = {"0", "0", "b", "2"}, -- SUPERSCRIPT TWO
  ["3S"]  = {"0", "0", "b", "3"}, -- SUPERSCRIPT THREE
  ["''"]  = {"0", "3", "0", "1"}, -- COMBINING ACUTE ACCENT
  ["My"]  = {"0", "0", "b", "5"}, -- MICRO SIGN
  ["PI"]  = {"0", "0", "b", "6"}, -- PILCROW SIGN
  [".M"]  = {"0", "0", "b", "7"}, -- MIDDLE DOT
  ["',"]  = {"0", "0", "b", "8"}, -- CEDILLA
  ["1S"]  = {"0", "0", "b", "9"}, -- SUPERSCRIPT ONE
  ["-o"]  = {"0", "0", "b", "a"}, -- MASCULINE ORDINAL INDICATOR
  [">>"]  = {"0", "0", "b", "b"}, -- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
  ["14"]  = {"0", "0", "b", "c"}, -- VULGAR FRACTION ONE QUARTER
  ["12"]  = {"0", "0", "b", "d"}, -- VULGAR FRACTION ONE HALF
  ["34"]  = {"0", "0", "b", "e"}, -- VULGAR FRACTION THREE QUARTERS
  ["?I"]  = {"0", "0", "b", "f"}, -- INVERTED QUESTION MARK
  ["A!"]  = {"0", "0", "c", "0"}, -- LATIN CAPITAL LETTER A WITH GRAVE
  ["A'"]  = {"0", "0", "c", "1"}, -- LATIN CAPITAL LETTER A WITH ACUTE
  ["A>"]  = {"0", "0", "c", "2"}, -- LATIN CAPITAL LETTER A WITH CIRCUMFLEX
  ["A?"]  = {"0", "0", "c", "3"}, -- LATIN CAPITAL LETTER A WITH TILDE
  ["A:"]  = {"0", "0", "c", "4"}, -- LATIN CAPITAL LETTER A WITH DIAERESIS
  ["AA"]  = {"0", "0", "c", "5"}, -- LATIN CAPITAL LETTER A WITH RING ABOVE
  ["AE"]  = {"0", "0", "c", "6"}, -- LATIN CAPITAL LETTER AE
  ["C,"]  = {"0", "0", "c", "7"}, -- LATIN CAPITAL LETTER C WITH CEDILLA
  ["E!"]  = {"0", "0", "c", "8"}, -- LATIN CAPITAL LETTER E WITH GRAVE
  ["E'"]  = {"0", "0", "c", "9"}, -- LATIN CAPITAL LETTER E WITH ACUTE
  ["E>"]  = {"0", "0", "c", "a"}, -- LATIN CAPITAL LETTER E WITH CIRCUMFLEX
  ["E:"]  = {"0", "0", "c", "b"}, -- LATIN CAPITAL LETTER E WITH DIAERESIS
  ["I!"]  = {"0", "0", "c", "c"}, -- LATIN CAPITAL LETTER I WITH GRAVE
  ["I'"]  = {"0", "0", "c", "d"}, -- LATIN CAPITAL LETTER I WITH ACUTE
  ["I>"]  = {"0", "0", "c", "e"}, -- LATIN CAPITAL LETTER I WITH CIRCUMFLEX
  ["I:"]  = {"0", "0", "c", "f"}, -- LATIN CAPITAL LETTER I WITH DIAERESIS
  ["D-"]  = {"0", "0", "d", "0"}, -- LATIN CAPITAL LETTER ETH
  ["N?"]  = {"0", "0", "d", "1"}, -- LATIN CAPITAL LETTER N WITH TILDE
  ["O!"]  = {"0", "0", "d", "2"}, -- LATIN CAPITAL LETTER O WITH GRAVE
  ["O'"]  = {"0", "0", "d", "3"}, -- LATIN CAPITAL LETTER O WITH ACUTE
  ["O>"]  = {"0", "0", "d", "4"}, -- LATIN CAPITAL LETTER O WITH CIRCUMFLEX
  ["O?"]  = {"0", "0", "d", "5"}, -- LATIN CAPITAL LETTER O WITH TILDE
  ["O:"]  = {"0", "0", "d", "6"}, -- LATIN CAPITAL LETTER O WITH DIAERESIS
  ["*X"]  = {"0", "0", "d", "7"}, -- MULTIPLICATION SIGN
  ["O/"]  = {"0", "0", "d", "8"}, -- LATIN CAPITAL LETTER O WITH STROKE
  ["U!"]  = {"0", "0", "d", "9"}, -- LATIN CAPITAL LETTER U WITH GRAVE
  ["U'"]  = {"0", "0", "d", "a"}, -- LATIN CAPITAL LETTER U WITH ACUTE
  ["U>"]  = {"0", "0", "d", "b"}, -- LATIN CAPITAL LETTER U WITH CIRCUMFLEX
  ["U:"]  = {"0", "0", "d", "c"}, -- LATIN CAPITAL LETTER U WITH DIAERESIS
  ["Y'"]  = {"0", "0", "d", "d"}, -- LATIN CAPITAL LETTER Y WITH ACUTE
  ["TH"]  = {"0", "0", "d", "e"}, -- LATIN CAPITAL LETTER THORN
  ["ss"]  = {"0", "0", "d", "f"}, -- LATIN SMALL LETTER SHARP S
  ["a!"]  = {"0", "0", "e", "0"}, -- LATIN SMALL LETTER A WITH GRAVE
  ["a'"]  = {"0", "0", "e", "1"}, -- LATIN SMALL LETTER A WITH ACUTE
  ["a>"]  = {"0", "0", "e", "2"}, -- LATIN SMALL LETTER A WITH CIRCUMFLEX
  ["a?"]  = {"0", "0", "e", "3"}, -- LATIN SMALL LETTER A WITH TILDE
  ["a:"]  = {"0", "0", "e", "4"}, -- LATIN SMALL LETTER A WITH DIAERESIS
  ["aa"]  = {"0", "0", "e", "5"}, -- LATIN SMALL LETTER A WITH RING ABOVE
  ["ae"]  = {"0", "0", "e", "6"}, -- LATIN SMALL LETTER AE
  ["c,"]  = {"0", "0", "e", "7"}, -- LATIN SMALL LETTER C WITH CEDILLA
  ["e!"]  = {"0", "0", "e", "8"}, -- LATIN SMALL LETTER E WITH GRAVE
  ["e'"]  = {"0", "0", "e", "9"}, -- LATIN SMALL LETTER E WITH ACUTE
  ["e>"]  = {"0", "0", "e", "a"}, -- LATIN SMALL LETTER E WITH CIRCUMFLEX
  ["e:"]  = {"0", "0", "e", "b"}, -- LATIN SMALL LETTER E WITH DIAERESIS
  ["i!"]  = {"0", "0", "e", "c"}, -- LATIN SMALL LETTER I WITH GRAVE
  ["i'"]  = {"0", "0", "e", "d"}, -- LATIN SMALL LETTER I WITH ACUTE
  ["i>"]  = {"0", "0", "e", "e"}, -- LATIN SMALL LETTER I WITH CIRCUMFLEX
  ["i:"]  = {"0", "0", "e", "f"}, -- LATIN SMALL LETTER I WITH DIAERESIS
  ["d-"]  = {"0", "0", "f", "0"}, -- LATIN SMALL LETTER ETH
  ["n?"]  = {"0", "0", "f", "1"}, -- LATIN SMALL LETTER N WITH TILDE
  ["o!"]  = {"0", "0", "f", "2"}, -- LATIN SMALL LETTER O WITH GRAVE
  ["o'"]  = {"0", "0", "f", "3"}, -- LATIN SMALL LETTER O WITH ACUTE
  ["o>"]  = {"0", "0", "f", "4"}, -- LATIN SMALL LETTER O WITH CIRCUMFLEX
  ["o?"]  = {"0", "0", "f", "5"}, -- LATIN SMALL LETTER O WITH TILDE
  ["o:"]  = {"0", "0", "f", "6"}, -- LATIN SMALL LETTER O WITH DIAERESIS
  ["-:"]  = {"0", "0", "f", "7"}, -- DIVISION SIGN
  ["o/"]  = {"0", "0", "f", "8"}, -- LATIN SMALL LETTER O WITH STROKE
  ["u!"]  = {"0", "0", "f", "9"}, -- LATIN SMALL LETTER U WITH GRAVE
  ["u'"]  = {"0", "0", "f", "a"}, -- LATIN SMALL LETTER U WITH ACUTE
  ["u>"]  = {"0", "0", "f", "b"}, -- LATIN SMALL LETTER U WITH CIRCUMFLEX
  ["u:"]  = {"0", "0", "f", "c"}, -- LATIN SMALL LETTER U WITH DIAERESIS
  ["y'"]  = {"0", "0", "f", "d"}, -- LATIN SMALL LETTER Y WITH ACUTE
  ["th"]  = {"0", "0", "f", "e"}, -- LATIN SMALL LETTER THORN
  ["y:"]  = {"0", "0", "f", "f"}, -- LATIN SMALL LETTER Y WITH DIAERESIS
  ["A-"]  = {"0", "1", "0", "0"}, -- LATIN CAPITAL LETTER A WITH MACRON
  ["a-"]  = {"0", "1", "0", "1"}, -- LATIN SMALL LETTER A WITH MACRON
  ["A("]  = {"0", "1", "0", "2"}, -- LATIN CAPITAL LETTER A WITH BREVE
  ["a("]  = {"0", "1", "0", "3"}, -- LATIN SMALL LETTER A WITH BREVE
  ["A;"]  = {"0", "1", "0", "4"}, -- LATIN CAPITAL LETTER A WITH OGONEK
  ["a;"]  = {"0", "1", "0", "5"}, -- LATIN SMALL LETTER A WITH OGONEK
  ["C'"]  = {"0", "1", "0", "6"}, -- LATIN CAPITAL LETTER C WITH ACUTE
  ["c'"]  = {"0", "1", "0", "7"}, -- LATIN SMALL LETTER C WITH ACUTE
  ["C>"]  = {"0", "1", "0", "8"}, -- LATIN CAPITAL LETTER C WITH CIRCUMFLEX
  ["c>"]  = {"0", "1", "0", "9"}, -- LATIN SMALL LETTER C WITH CIRCUMFLEX
  ["C."]  = {"0", "1", "0", "a"}, -- LATIN CAPITAL LETTER C WITH DOT ABOVE
  ["c."]  = {"0", "1", "0", "b"}, -- LATIN SMALL LETTER C WITH DOT ABOVE
  ["C<"]  = {"0", "1", "0", "c"}, -- LATIN CAPITAL LETTER C WITH CARON
  ["c<"]  = {"0", "1", "0", "d"}, -- LATIN SMALL LETTER C WITH CARON
  ["D<"]  = {"0", "1", "0", "e"}, -- LATIN CAPITAL LETTER D WITH CARON
  ["d<"]  = {"0", "1", "0", "f"}, -- LATIN SMALL LETTER D WITH CARON
  ["D/"]  = {"0", "1", "1", "0"}, -- LATIN CAPITAL LETTER D WITH STROKE
  ["d/"]  = {"0", "1", "1", "1"}, -- LATIN SMALL LETTER D WITH STROKE
  ["E-"]  = {"0", "1", "1", "2"}, -- LATIN CAPITAL LETTER E WITH MACRON
  ["e-"]  = {"0", "1", "1", "3"}, -- LATIN SMALL LETTER E WITH MACRON
  ["E("]  = {"0", "1", "1", "4"}, -- LATIN CAPITAL LETTER E WITH BREVE
  ["e("]  = {"0", "1", "1", "5"}, -- LATIN SMALL LETTER E WITH BREVE
  ["E."]  = {"0", "1", "1", "6"}, -- LATIN CAPITAL LETTER E WITH DOT ABOVE
  ["e."]  = {"0", "1", "1", "7"}, -- LATIN SMALL LETTER E WITH DOT ABOVE
  ["E;"]  = {"0", "1", "1", "8"}, -- LATIN CAPITAL LETTER E WITH OGONEK
  ["e;"]  = {"0", "1", "1", "9"}, -- LATIN SMALL LETTER E WITH OGONEK
  ["E<"]  = {"0", "1", "1", "a"}, -- LATIN CAPITAL LETTER E WITH CARON
  ["e<"]  = {"0", "1", "1", "b"}, -- LATIN SMALL LETTER E WITH CARON
  ["G>"]  = {"0", "1", "1", "c"}, -- LATIN CAPITAL LETTER G WITH CIRCUMFLEX
  ["g>"]  = {"0", "1", "1", "d"}, -- LATIN SMALL LETTER G WITH CIRCUMFLEX
  ["G("]  = {"0", "1", "1", "e"}, -- LATIN CAPITAL LETTER G WITH BREVE
  ["g("]  = {"0", "1", "1", "f"}, -- LATIN SMALL LETTER G WITH BREVE
  ["G."]  = {"0", "1", "2", "0"}, -- LATIN CAPITAL LETTER G WITH DOT ABOVE
  ["g."]  = {"0", "1", "2", "1"}, -- LATIN SMALL LETTER G WITH DOT ABOVE
  ["G,"]  = {"0", "1", "2", "2"}, -- LATIN CAPITAL LETTER G WITH CEDILLA
  ["g,"]  = {"0", "1", "2", "3"}, -- LATIN SMALL LETTER G WITH CEDILLA
  ["H>"]  = {"0", "1", "2", "4"}, -- LATIN CAPITAL LETTER H WITH CIRCUMFLEX
  ["h>"]  = {"0", "1", "2", "5"}, -- LATIN SMALL LETTER H WITH CIRCUMFLEX
  ["H/"]  = {"0", "1", "2", "6"}, -- LATIN CAPITAL LETTER H WITH STROKE
  ["h/"]  = {"0", "1", "2", "7"}, -- LATIN SMALL LETTER H WITH STROKE
  ["I?"]  = {"0", "1", "2", "8"}, -- LATIN CAPITAL LETTER I WITH TILDE
  ["i?"]  = {"0", "1", "2", "9"}, -- LATIN SMALL LETTER I WITH TILDE
  ["I-"]  = {"0", "1", "2", "a"}, -- LATIN CAPITAL LETTER I WITH MACRON
  ["i-"]  = {"0", "1", "2", "b"}, -- LATIN SMALL LETTER I WITH MACRON
  ["I("]  = {"0", "1", "2", "c"}, -- LATIN CAPITAL LETTER I WITH BREVE
  ["i("]  = {"0", "1", "2", "d"}, -- LATIN SMALL LETTER I WITH BREVE
  ["I;"]  = {"0", "1", "2", "e"}, -- LATIN CAPITAL LETTER I WITH OGONEK
  ["i;"]  = {"0", "1", "2", "f"}, -- LATIN SMALL LETTER I WITH OGONEK
  ["I."]  = {"0", "1", "3", "0"}, -- LATIN CAPITAL LETTER I WITH DOT ABOVE
  ["i."]  = {"0", "1", "3", "1"}, -- LATIN SMALL LETTER DOTLESS I
  ["IJ"]  = {"0", "1", "3", "2"}, -- LATIN CAPITAL LIGATURE IJ
  ["ij"]  = {"0", "1", "3", "3"}, -- LATIN SMALL LIGATURE IJ
  ["J>"]  = {"0", "1", "3", "4"}, -- LATIN CAPITAL LETTER J WITH CIRCUMFLEX
  ["j>"]  = {"0", "1", "3", "5"}, -- LATIN SMALL LETTER J WITH CIRCUMFLEX
  ["K,"]  = {"0", "1", "3", "6"}, -- LATIN CAPITAL LETTER K WITH CEDILLA
  ["k,"]  = {"0", "1", "3", "7"}, -- LATIN SMALL LETTER K WITH CEDILLA
  ["kk"]  = {"0", "1", "3", "8"}, -- LATIN SMALL LETTER KRA
  ["L'"]  = {"0", "1", "3", "9"}, -- LATIN CAPITAL LETTER L WITH ACUTE
  ["l'"]  = {"0", "1", "3", "a"}, -- LATIN SMALL LETTER L WITH ACUTE
  ["L,"]  = {"0", "1", "3", "b"}, -- LATIN CAPITAL LETTER L WITH CEDILLA
  ["l,"]  = {"0", "1", "3", "c"}, -- LATIN SMALL LETTER L WITH CEDILLA
  ["L<"]  = {"0", "1", "3", "d"}, -- LATIN CAPITAL LETTER L WITH CARON
  ["l<"]  = {"0", "1", "3", "e"}, -- LATIN SMALL LETTER L WITH CARON
  ["L."]  = {"0", "1", "3", "f"}, -- LATIN CAPITAL LETTER L WITH MIDDLE DOT
  ["l."]  = {"0", "1", "4", "0"}, -- LATIN SMALL LETTER L WITH MIDDLE DOT
  ["L/"]  = {"0", "1", "4", "1"}, -- LATIN CAPITAL LETTER L WITH STROKE
  ["l/"]  = {"0", "1", "4", "2"}, -- LATIN SMALL LETTER L WITH STROKE
  ["N'"]  = {"0", "1", "4", "3"}, -- LATIN CAPITAL LETTER N WITH ACUTE
  ["n'"]  = {"0", "1", "4", "4"}, -- LATIN SMALL LETTER N WITH ACUTE
  ["N,"]  = {"0", "1", "4", "5"}, -- LATIN CAPITAL LETTER N WITH CEDILLA
  ["n,"]  = {"0", "1", "4", "6"}, -- LATIN SMALL LETTER N WITH CEDILLA
  ["N<"]  = {"0", "1", "4", "7"}, -- LATIN CAPITAL LETTER N WITH CARON
  ["n<"]  = {"0", "1", "4", "8"}, -- LATIN SMALL LETTER N WITH CARON
  ["'n"]  = {"0", "1", "4", "9"}, -- LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
  ["NG"]  = {"0", "1", "4", "a"}, -- LATIN CAPITAL LETTER ENG
  ["ng"]  = {"0", "1", "4", "b"}, -- LATIN SMALL LETTER ENG
  ["O-"]  = {"0", "1", "4", "c"}, -- LATIN CAPITAL LETTER O WITH MACRON
  ["o-"]  = {"0", "1", "4", "d"}, -- LATIN SMALL LETTER O WITH MACRON
  ["O("]  = {"0", "1", "4", "e"}, -- LATIN CAPITAL LETTER O WITH BREVE
  ["o("]  = {"0", "1", "4", "f"}, -- LATIN SMALL LETTER O WITH BREVE
  ["O\""] = {"0", "1", "5", "0"}, -- LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
  ["o\""] = {"0", "1", "5", "1"}, -- LATIN SMALL LETTER O WITH DOUBLE ACUTE
  ["OE"]  = {"0", "1", "5", "2"}, -- LATIN CAPITAL LIGATURE OE
  ["oe"]  = {"0", "1", "5", "3"}, -- LATIN SMALL LIGATURE OE
  ["R'"]  = {"0", "1", "5", "4"}, -- LATIN CAPITAL LETTER R WITH ACUTE
  ["r'"]  = {"0", "1", "5", "5"}, -- LATIN SMALL LETTER R WITH ACUTE
  ["R,"]  = {"0", "1", "5", "6"}, -- LATIN CAPITAL LETTER R WITH CEDILLA
  ["r,"]  = {"0", "1", "5", "7"}, -- LATIN SMALL LETTER R WITH CEDILLA
  ["R<"]  = {"0", "1", "5", "8"}, -- LATIN CAPITAL LETTER R WITH CARON
  ["r<"]  = {"0", "1", "5", "9"}, -- LATIN SMALL LETTER R WITH CARON
  ["S'"]  = {"0", "1", "5", "a"}, -- LATIN CAPITAL LETTER S WITH ACUTE
  ["s'"]  = {"0", "1", "5", "b"}, -- LATIN SMALL LETTER S WITH ACUTE
  ["S>"]  = {"0", "1", "5", "c"}, -- LATIN CAPITAL LETTER S WITH CIRCUMFLEX
  ["s>"]  = {"0", "1", "5", "d"}, -- LATIN SMALL LETTER S WITH CIRCUMFLEX
  ["S,"]  = {"0", "1", "5", "e"}, -- LATIN CAPITAL LETTER S WITH CEDILLA
  ["s,"]  = {"0", "1", "5", "f"}, -- LATIN SMALL LETTER S WITH CEDILLA
  ["S<"]  = {"0", "1", "6", "0"}, -- LATIN CAPITAL LETTER S WITH CARON
  ["s<"]  = {"0", "1", "6", "1"}, -- LATIN SMALL LETTER S WITH CARON
  ["T,"]  = {"0", "1", "6", "2"}, -- LATIN CAPITAL LETTER T WITH CEDILLA
  ["t,"]  = {"0", "1", "6", "3"}, -- LATIN SMALL LETTER T WITH CEDILLA
  ["T<"]  = {"0", "1", "6", "4"}, -- LATIN CAPITAL LETTER T WITH CARON
  ["t<"]  = {"0", "1", "6", "5"}, -- LATIN SMALL LETTER T WITH CARON
  ["T/"]  = {"0", "1", "6", "6"}, -- LATIN CAPITAL LETTER T WITH STROKE
  ["t/"]  = {"0", "1", "6", "7"}, -- LATIN SMALL LETTER T WITH STROKE
  ["U?"]  = {"0", "1", "6", "8"}, -- LATIN CAPITAL LETTER U WITH TILDE
  ["u?"]  = {"0", "1", "6", "9"}, -- LATIN SMALL LETTER U WITH TILDE
  ["U-"]  = {"0", "1", "6", "a"}, -- LATIN CAPITAL LETTER U WITH MACRON
  ["u-"]  = {"0", "1", "6", "b"}, -- LATIN SMALL LETTER U WITH MACRON
  ["U("]  = {"0", "1", "6", "c"}, -- LATIN CAPITAL LETTER U WITH BREVE
  ["u("]  = {"0", "1", "6", "d"}, -- LATIN SMALL LETTER U WITH BREVE
  ["U0"]  = {"0", "1", "6", "e"}, -- LATIN CAPITAL LETTER U WITH RING ABOVE
  ["u0"]  = {"0", "1", "6", "f"}, -- LATIN SMALL LETTER U WITH RING ABOVE
  ["U\""] = {"0", "1", "7", "0"}, -- LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
  ["u\""] = {"0", "1", "7", "1"}, -- LATIN SMALL LETTER U WITH DOUBLE ACUTE
  ["U;"]  = {"0", "1", "7", "2"}, -- LATIN CAPITAL LETTER U WITH OGONEK
  ["u;"]  = {"0", "1", "7", "3"}, -- LATIN SMALL LETTER U WITH OGONEK
  ["W>"]  = {"0", "1", "7", "4"}, -- LATIN CAPITAL LETTER W WITH CIRCUMFLEX
  ["w>"]  = {"0", "1", "7", "5"}, -- LATIN SMALL LETTER W WITH CIRCUMFLEX
  ["Y>"]  = {"0", "1", "7", "6"}, -- LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
  ["y>"]  = {"0", "1", "7", "7"}, -- LATIN SMALL LETTER Y WITH CIRCUMFLEX
  ["Y:"]  = {"0", "1", "7", "8"}, -- LATIN CAPITAL LETTER Y WITH DIAERESIS
  ["Z'"]  = {"0", "1", "7", "9"}, -- LATIN CAPITAL LETTER Z WITH ACUTE
  ["z'"]  = {"0", "1", "7", "a"}, -- LATIN SMALL LETTER Z WITH ACUTE
  ["Z."]  = {"0", "1", "7", "b"}, -- LATIN CAPITAL LETTER Z WITH DOT ABOVE
  ["z."]  = {"0", "1", "7", "c"}, -- LATIN SMALL LETTER Z WITH DOT ABOVE
  ["Z<"]  = {"0", "1", "7", "d"}, -- LATIN CAPITAL LETTER Z WITH CARON
  ["z<"]  = {"0", "1", "7", "e"}, -- LATIN SMALL LETTER Z WITH CARON
  ["O9"]  = {"0", "1", "a", "0"}, -- LATIN CAPITAL LETTER O WITH HORN
  ["o9"]  = {"0", "1", "a", "1"}, -- LATIN SMALL LETTER O WITH HORN
  ["OI"]  = {"0", "1", "a", "2"}, -- LATIN CAPITAL LETTER GHA
  ["oi"]  = {"0", "1", "a", "3"}, -- LATIN SMALL LETTER GHA
  ["yr"]  = {"0", "1", "a", "6"}, -- LATIN LETTER YR
  ["U9"]  = {"0", "1", "a", "f"}, -- LATIN CAPITAL LETTER U WITH HORN
  ["u9"]  = {"0", "1", "b", "0"}, -- LATIN SMALL LETTER U WITH HORN
  ["Z/"]  = {"0", "1", "b", "5"}, -- LATIN CAPITAL LETTER Z WITH STROKE
  ["z/"]  = {"0", "1", "b", "6"}, -- LATIN SMALL LETTER Z WITH STROKE
  ["ED"]  = {"0", "1", "b", "7"}, -- LATIN CAPITAL LETTER EZH
  ["A<"]  = {"0", "1", "c", "d"}, -- LATIN CAPITAL LETTER A WITH CARON
  ["a<"]  = {"0", "1", "c", "e"}, -- LATIN SMALL LETTER A WITH CARON
  ["I<"]  = {"0", "1", "c", "f"}, -- LATIN CAPITAL LETTER I WITH CARON
  ["i<"]  = {"0", "1", "d", "0"}, -- LATIN SMALL LETTER I WITH CARON
  ["O<"]  = {"0", "1", "d", "1"}, -- LATIN CAPITAL LETTER O WITH CARON
  ["o<"]  = {"0", "1", "d", "2"}, -- LATIN SMALL LETTER O WITH CARON
  ["U<"]  = {"0", "1", "d", "3"}, -- LATIN CAPITAL LETTER U WITH CARON
  ["u<"]  = {"0", "1", "d", "4"}, -- LATIN SMALL LETTER U WITH CARON
  ["A1"]  = {"0", "1", "d", "e"}, -- LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
  ["a1"]  = {"0", "1", "d", "f"}, -- LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
  ["A7"]  = {"0", "1", "e", "0"}, -- LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
  ["a7"]  = {"0", "1", "e", "1"}, -- LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
  ["A3"]  = {"0", "1", "e", "2"}, -- LATIN CAPITAL LETTER AE WITH MACRON
  ["a3"]  = {"0", "1", "e", "3"}, -- LATIN SMALL LETTER AE WITH MACRON
  ["G/"]  = {"0", "1", "e", "4"}, -- LATIN CAPITAL LETTER G WITH STROKE
  ["g/"]  = {"0", "1", "e", "5"}, -- LATIN SMALL LETTER G WITH STROKE
  ["G<"]  = {"0", "1", "e", "6"}, -- LATIN CAPITAL LETTER G WITH CARON
  ["g<"]  = {"0", "1", "e", "7"}, -- LATIN SMALL LETTER G WITH CARON
  ["K<"]  = {"0", "1", "e", "8"}, -- LATIN CAPITAL LETTER K WITH CARON
  ["k<"]  = {"0", "1", "e", "9"}, -- LATIN SMALL LETTER K WITH CARON
  ["O;"]  = {"0", "1", "e", "a"}, -- LATIN CAPITAL LETTER O WITH OGONEK
  ["o;"]  = {"0", "1", "e", "b"}, -- LATIN SMALL LETTER O WITH OGONEK
  ["O1"]  = {"0", "1", "e", "c"}, -- LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
  ["o1"]  = {"0", "1", "e", "d"}, -- LATIN SMALL LETTER O WITH OGONEK AND MACRON
  ["EZ"]  = {"0", "1", "e", "e"}, -- LATIN CAPITAL LETTER EZH WITH CARON
  ["ez"]  = {"0", "1", "e", "f"}, -- LATIN SMALL LETTER EZH WITH CARON
  ["j<"]  = {"0", "1", "f", "0"}, -- LATIN SMALL LETTER J WITH CARON
  ["G'"]  = {"0", "1", "f", "4"}, -- LATIN CAPITAL LETTER G WITH ACUTE
  ["g'"]  = {"0", "1", "f", "5"}, -- LATIN SMALL LETTER G WITH ACUTE
  [";S"]  = {"0", "2", "b", "f"}, -- MODIFIER LETTER LEFT HALF RING
  ["'<"]  = {"0", "2", "c", "7"}, -- CARON
  ["'("]  = {"0", "2", "d", "8"}, -- BREVE
  ["'."]  = {"0", "2", "d", "9"}, -- DOT ABOVE
  ["'0"]  = {"0", "2", "d", "a"}, -- RING ABOVE
  ["';"]  = {"0", "2", "d", "b"}, -- OGONEK
  ["'\""] = {"0", "2", "d", "d"}, -- DOUBLE ACUTE ACCENT
  ["A%"]  = {"0", "3", "8", "6"}, -- GREEK CAPITAL LETTER ALPHA WITH TONOS
  ["E%"]  = {"0", "3", "8", "8"}, -- GREEK CAPITAL LETTER EPSILON WITH TONOS
  ["Y%"]  = {"0", "3", "8", "9"}, -- GREEK CAPITAL LETTER ETA WITH TONOS
  ["I%"]  = {"0", "3", "8", "a"}, -- GREEK CAPITAL LETTER IOTA WITH TONOS
  ["O%"]  = {"0", "3", "8", "c"}, -- GREEK CAPITAL LETTER OMICRON WITH TONOS
  ["U%"]  = {"0", "3", "8", "e"}, -- GREEK CAPITAL LETTER UPSILON WITH TONOS
  ["W%"]  = {"0", "3", "8", "f"}, -- GREEK CAPITAL LETTER OMEGA WITH TONOS
  ["i3"]  = {"0", "3", "9", "0"}, -- GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
  ["A*"]  = {"0", "3", "9", "1"}, -- GREEK CAPITAL LETTER ALPHA
  ["B*"]  = {"0", "3", "9", "2"}, -- GREEK CAPITAL LETTER BETA
  ["G*"]  = {"0", "3", "9", "3"}, -- GREEK CAPITAL LETTER GAMMA
  ["D*"]  = {"0", "3", "9", "4"}, -- GREEK CAPITAL LETTER DELTA
  ["E*"]  = {"0", "3", "9", "5"}, -- GREEK CAPITAL LETTER EPSILON
  ["Z*"]  = {"0", "3", "9", "6"}, -- GREEK CAPITAL LETTER ZETA
  ["Y*"]  = {"0", "3", "9", "7"}, -- GREEK CAPITAL LETTER ETA
  ["H*"]  = {"0", "3", "9", "8"}, -- GREEK CAPITAL LETTER THETA
  ["I*"]  = {"0", "3", "9", "9"}, -- GREEK CAPITAL LETTER IOTA
  ["K*"]  = {"0", "3", "9", "a"}, -- GREEK CAPITAL LETTER KAPPA
  ["L*"]  = {"0", "3", "9", "b"}, -- GREEK CAPITAL LETTER LAMDA
  ["M*"]  = {"0", "3", "9", "c"}, -- GREEK CAPITAL LETTER MU
  ["N*"]  = {"0", "3", "9", "d"}, -- GREEK CAPITAL LETTER NU
  ["C*"]  = {"0", "3", "9", "e"}, -- GREEK CAPITAL LETTER XI
  ["O*"]  = {"0", "3", "9", "f"}, -- GREEK CAPITAL LETTER OMICRON
  ["P*"]  = {"0", "3", "a", "0"}, -- GREEK CAPITAL LETTER PI
  ["R*"]  = {"0", "3", "a", "1"}, -- GREEK CAPITAL LETTER RHO
  ["S*"]  = {"0", "3", "a", "3"}, -- GREEK CAPITAL LETTER SIGMA
  ["T*"]  = {"0", "3", "a", "4"}, -- GREEK CAPITAL LETTER TAU
  ["U*"]  = {"0", "3", "a", "5"}, -- GREEK CAPITAL LETTER UPSILON
  ["F*"]  = {"0", "3", "a", "6"}, -- GREEK CAPITAL LETTER PHI
  ["X*"]  = {"0", "3", "a", "7"}, -- GREEK CAPITAL LETTER CHI
  ["Q*"]  = {"0", "3", "a", "8"}, -- GREEK CAPITAL LETTER PSI
  ["W*"]  = {"0", "3", "a", "9"}, -- GREEK CAPITAL LETTER OMEGA
  ["J*"]  = {"0", "3", "a", "a"}, -- GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
  ["V*"]  = {"0", "3", "a", "b"}, -- GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
  ["a%"]  = {"0", "3", "a", "c"}, -- GREEK SMALL LETTER ALPHA WITH TONOS
  ["e%"]  = {"0", "3", "a", "d"}, -- GREEK SMALL LETTER EPSILON WITH TONOS
  ["y%"]  = {"0", "3", "a", "e"}, -- GREEK SMALL LETTER ETA WITH TONOS
  ["i%"]  = {"0", "3", "a", "f"}, -- GREEK SMALL LETTER IOTA WITH TONOS
  ["u3"]  = {"0", "3", "b", "0"}, -- GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
  ["a*"]  = {"0", "3", "b", "1"}, -- GREEK SMALL LETTER ALPHA
  ["b*"]  = {"0", "3", "b", "2"}, -- GREEK SMALL LETTER BETA
  ["g*"]  = {"0", "3", "b", "3"}, -- GREEK SMALL LETTER GAMMA
  ["d*"]  = {"0", "3", "b", "4"}, -- GREEK SMALL LETTER DELTA
  ["e*"]  = {"0", "3", "b", "5"}, -- GREEK SMALL LETTER EPSILON
  ["z*"]  = {"0", "3", "b", "6"}, -- GREEK SMALL LETTER ZETA
  ["y*"]  = {"0", "3", "b", "7"}, -- GREEK SMALL LETTER ETA
  ["h*"]  = {"0", "3", "b", "8"}, -- GREEK SMALL LETTER THETA
  ["i*"]  = {"0", "3", "b", "9"}, -- GREEK SMALL LETTER IOTA
  ["k*"]  = {"0", "3", "b", "a"}, -- GREEK SMALL LETTER KAPPA
  ["l*"]  = {"0", "3", "b", "b"}, -- GREEK SMALL LETTER LAMDA
  ["m*"]  = {"0", "3", "b", "c"}, -- GREEK SMALL LETTER MU
  ["n*"]  = {"0", "3", "b", "d"}, -- GREEK SMALL LETTER NU
  ["c*"]  = {"0", "3", "b", "e"}, -- GREEK SMALL LETTER XI
  ["o*"]  = {"0", "3", "b", "f"}, -- GREEK SMALL LETTER OMICRON
  ["p*"]  = {"0", "3", "c", "0"}, -- GREEK SMALL LETTER PI
  ["r*"]  = {"0", "3", "c", "1"}, -- GREEK SMALL LETTER RHO
  ["*s"]  = {"0", "3", "c", "2"}, -- GREEK SMALL LETTER FINAL SIGMA
  ["s*"]  = {"0", "3", "c", "3"}, -- GREEK SMALL LETTER SIGMA
  ["t*"]  = {"0", "3", "c", "4"}, -- GREEK SMALL LETTER TAU
  ["u*"]  = {"0", "3", "c", "5"}, -- GREEK SMALL LETTER UPSILON
  ["f*"]  = {"0", "3", "c", "6"}, -- GREEK SMALL LETTER PHI
  ["x*"]  = {"0", "3", "c", "7"}, -- GREEK SMALL LETTER CHI
  ["q*"]  = {"0", "3", "c", "8"}, -- GREEK SMALL LETTER PSI
  ["w*"]  = {"0", "3", "c", "9"}, -- GREEK SMALL LETTER OMEGA
  ["j*"]  = {"0", "3", "c", "a"}, -- GREEK SMALL LETTER IOTA WITH DIALYTIKA
  ["v*"]  = {"0", "3", "c", "b"}, -- GREEK SMALL LETTER UPSILON WITH DIALYTIKA
  ["o%"]  = {"0", "3", "c", "c"}, -- GREEK SMALL LETTER OMICRON WITH TONOS
  ["u%"]  = {"0", "3", "c", "d"}, -- GREEK SMALL LETTER UPSILON WITH TONOS
  ["w%"]  = {"0", "3", "c", "e"}, -- GREEK SMALL LETTER OMEGA WITH TONOS
  ["'G"]  = {"0", "3", "d", "8"}, -- GREEK LETTER ARCHAIC KOPPA
  [",G"]  = {"0", "3", "d", "9"}, -- GREEK SMALL LETTER ARCHAIC KOPPA
  ["T3"]  = {"0", "3", "d", "a"}, -- GREEK LETTER STIGMA
  ["t3"]  = {"0", "3", "d", "b"}, -- GREEK SMALL LETTER STIGMA
  ["M3"]  = {"0", "3", "d", "c"}, -- GREEK LETTER DIGAMMA
  ["m3"]  = {"0", "3", "d", "d"}, -- GREEK SMALL LETTER DIGAMMA
  ["K3"]  = {"0", "3", "d", "e"}, -- GREEK LETTER KOPPA
  ["k3"]  = {"0", "3", "d", "f"}, -- GREEK SMALL LETTER KOPPA
  ["P3"]  = {"0", "3", "e", "0"}, -- GREEK LETTER SAMPI
  ["p3"]  = {"0", "3", "e", "1"}, -- GREEK SMALL LETTER SAMPI
  ["'%"]  = {"0", "3", "f", "4"}, -- GREEK CAPITAL THETA SYMBOL
  ["j3"]  = {"0", "3", "f", "5"}, -- GREEK LUNATE EPSILON SYMBOL
  ["IO"]  = {"0", "4", "0", "1"}, -- CYRILLIC CAPITAL LETTER IO
  ["D%"]  = {"0", "4", "0", "2"}, -- CYRILLIC CAPITAL LETTER DJE
  ["G%"]  = {"0", "4", "0", "3"}, -- CYRILLIC CAPITAL LETTER GJE
  ["IE"]  = {"0", "4", "0", "4"}, -- CYRILLIC CAPITAL LETTER UKRAINIAN IE
  ["DS"]  = {"0", "4", "0", "5"}, -- CYRILLIC CAPITAL LETTER DZE
  ["II"]  = {"0", "4", "0", "6"}, -- CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
  ["YI"]  = {"0", "4", "0", "7"}, -- CYRILLIC CAPITAL LETTER YI
  ["J%"]  = {"0", "4", "0", "8"}, -- CYRILLIC CAPITAL LETTER JE
  ["LJ"]  = {"0", "4", "0", "9"}, -- CYRILLIC CAPITAL LETTER LJE
  ["NJ"]  = {"0", "4", "0", "a"}, -- CYRILLIC CAPITAL LETTER NJE
  ["Ts"]  = {"0", "4", "0", "b"}, -- CYRILLIC CAPITAL LETTER TSHE
  ["KJ"]  = {"0", "4", "0", "c"}, -- CYRILLIC CAPITAL LETTER KJE
  ["V%"]  = {"0", "4", "0", "e"}, -- CYRILLIC CAPITAL LETTER SHORT U
  ["DZ"]  = {"0", "4", "0", "f"}, -- CYRILLIC CAPITAL LETTER DZHE
  ["A="]  = {"0", "4", "1", "0"}, -- CYRILLIC CAPITAL LETTER A
  ["B="]  = {"0", "4", "1", "1"}, -- CYRILLIC CAPITAL LETTER BE
  ["V="]  = {"0", "4", "1", "2"}, -- CYRILLIC CAPITAL LETTER VE
  ["G="]  = {"0", "4", "1", "3"}, -- CYRILLIC CAPITAL LETTER GHE
  ["D="]  = {"0", "4", "1", "4"}, -- CYRILLIC CAPITAL LETTER DE
  ["E="]  = {"0", "4", "1", "5"}, -- CYRILLIC CAPITAL LETTER IE
  ["Z%"]  = {"0", "4", "1", "6"}, -- CYRILLIC CAPITAL LETTER ZHE
  ["Z="]  = {"0", "4", "1", "7"}, -- CYRILLIC CAPITAL LETTER ZE
  ["I="]  = {"0", "4", "1", "8"}, -- CYRILLIC CAPITAL LETTER I
  ["J="]  = {"0", "4", "1", "9"}, -- CYRILLIC CAPITAL LETTER SHORT I
  ["K="]  = {"0", "4", "1", "a"}, -- CYRILLIC CAPITAL LETTER KA
  ["L="]  = {"0", "4", "1", "b"}, -- CYRILLIC CAPITAL LETTER EL
  ["M="]  = {"0", "4", "1", "c"}, -- CYRILLIC CAPITAL LETTER EM
  ["N="]  = {"0", "4", "1", "d"}, -- CYRILLIC CAPITAL LETTER EN
  ["O="]  = {"0", "4", "1", "e"}, -- CYRILLIC CAPITAL LETTER O
  ["P="]  = {"0", "4", "1", "f"}, -- CYRILLIC CAPITAL LETTER PE
  ["R="]  = {"0", "4", "2", "0"}, -- CYRILLIC CAPITAL LETTER ER
  ["S="]  = {"0", "4", "2", "1"}, -- CYRILLIC CAPITAL LETTER ES
  ["T="]  = {"0", "4", "2", "2"}, -- CYRILLIC CAPITAL LETTER TE
  ["U="]  = {"0", "4", "2", "3"}, -- CYRILLIC CAPITAL LETTER U
  ["F="]  = {"0", "4", "2", "4"}, -- CYRILLIC CAPITAL LETTER EF
  ["H="]  = {"0", "4", "2", "5"}, -- CYRILLIC CAPITAL LETTER HA
  ["C="]  = {"0", "4", "2", "6"}, -- CYRILLIC CAPITAL LETTER TSE
  ["C%"]  = {"0", "4", "2", "7"}, -- CYRILLIC CAPITAL LETTER CHE
  ["S%"]  = {"0", "4", "2", "8"}, -- CYRILLIC CAPITAL LETTER SHA
  ["Sc"]  = {"0", "4", "2", "9"}, -- CYRILLIC CAPITAL LETTER SHCHA
  ["=\""] = {"0", "4", "2", "a"}, -- CYRILLIC CAPITAL LETTER HARD SIGN
  ["Y="]  = {"0", "4", "2", "b"}, -- CYRILLIC CAPITAL LETTER YERU
  ["%\""] = {"0", "4", "2", "c"}, -- CYRILLIC CAPITAL LETTER SOFT SIGN
  ["JE"]  = {"0", "4", "2", "d"}, -- CYRILLIC CAPITAL LETTER E
  ["JU"]  = {"0", "4", "2", "e"}, -- CYRILLIC CAPITAL LETTER YU
  ["JA"]  = {"0", "4", "2", "f"}, -- CYRILLIC CAPITAL LETTER YA
  ["a="]  = {"0", "4", "3", "0"}, -- CYRILLIC SMALL LETTER A
  ["b="]  = {"0", "4", "3", "1"}, -- CYRILLIC SMALL LETTER BE
  ["v="]  = {"0", "4", "3", "2"}, -- CYRILLIC SMALL LETTER VE
  ["g="]  = {"0", "4", "3", "3"}, -- CYRILLIC SMALL LETTER GHE
  ["d="]  = {"0", "4", "3", "4"}, -- CYRILLIC SMALL LETTER DE
  ["e="]  = {"0", "4", "3", "5"}, -- CYRILLIC SMALL LETTER IE
  ["z%"]  = {"0", "4", "3", "6"}, -- CYRILLIC SMALL LETTER ZHE
  ["z="]  = {"0", "4", "3", "7"}, -- CYRILLIC SMALL LETTER ZE
  ["i="]  = {"0", "4", "3", "8"}, -- CYRILLIC SMALL LETTER I
  ["j="]  = {"0", "4", "3", "9"}, -- CYRILLIC SMALL LETTER SHORT I
  ["k="]  = {"0", "4", "3", "a"}, -- CYRILLIC SMALL LETTER KA
  ["l="]  = {"0", "4", "3", "b"}, -- CYRILLIC SMALL LETTER EL
  ["m="]  = {"0", "4", "3", "c"}, -- CYRILLIC SMALL LETTER EM
  ["n="]  = {"0", "4", "3", "d"}, -- CYRILLIC SMALL LETTER EN
  ["o="]  = {"0", "4", "3", "e"}, -- CYRILLIC SMALL LETTER O
  ["p="]  = {"0", "4", "3", "f"}, -- CYRILLIC SMALL LETTER PE
  ["r="]  = {"0", "4", "4", "0"}, -- CYRILLIC SMALL LETTER ER
  ["s="]  = {"0", "4", "4", "1"}, -- CYRILLIC SMALL LETTER ES
  ["t="]  = {"0", "4", "4", "2"}, -- CYRILLIC SMALL LETTER TE
  ["u="]  = {"0", "4", "4", "3"}, -- CYRILLIC SMALL LETTER U
  ["f="]  = {"0", "4", "4", "4"}, -- CYRILLIC SMALL LETTER EF
  ["h="]  = {"0", "4", "4", "5"}, -- CYRILLIC SMALL LETTER HA
  ["c="]  = {"0", "4", "4", "6"}, -- CYRILLIC SMALL LETTER TSE
  ["c%"]  = {"0", "4", "4", "7"}, -- CYRILLIC SMALL LETTER CHE
  ["s%"]  = {"0", "4", "4", "8"}, -- CYRILLIC SMALL LETTER SHA
  ["sc"]  = {"0", "4", "4", "9"}, -- CYRILLIC SMALL LETTER SHCHA
  ["='"]  = {"0", "4", "4", "a"}, -- CYRILLIC SMALL LETTER HARD SIGN
  ["y="]  = {"0", "4", "4", "b"}, -- CYRILLIC SMALL LETTER YERU
  ["%'"]  = {"0", "4", "4", "c"}, -- CYRILLIC SMALL LETTER SOFT SIGN
  ["je"]  = {"0", "4", "4", "d"}, -- CYRILLIC SMALL LETTER E
  ["ju"]  = {"0", "4", "4", "e"}, -- CYRILLIC SMALL LETTER YU
  ["ja"]  = {"0", "4", "4", "f"}, -- CYRILLIC SMALL LETTER YA
  ["io"]  = {"0", "4", "5", "1"}, -- CYRILLIC SMALL LETTER IO
  ["d%"]  = {"0", "4", "5", "2"}, -- CYRILLIC SMALL LETTER DJE
  ["g%"]  = {"0", "4", "5", "3"}, -- CYRILLIC SMALL LETTER GJE
  ["ie"]  = {"0", "4", "5", "4"}, -- CYRILLIC SMALL LETTER UKRAINIAN IE
  ["ds"]  = {"0", "4", "5", "5"}, -- CYRILLIC SMALL LETTER DZE
  ["ii"]  = {"0", "4", "5", "6"}, -- CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
  ["yi"]  = {"0", "4", "5", "7"}, -- CYRILLIC SMALL LETTER YI
  ["j%"]  = {"0", "4", "5", "8"}, -- CYRILLIC SMALL LETTER JE
  ["lj"]  = {"0", "4", "5", "9"}, -- CYRILLIC SMALL LETTER LJE
  ["nj"]  = {"0", "4", "5", "a"}, -- CYRILLIC SMALL LETTER NJE
  ["ts"]  = {"0", "4", "5", "b"}, -- CYRILLIC SMALL LETTER TSHE
  ["kj"]  = {"0", "4", "5", "c"}, -- CYRILLIC SMALL LETTER KJE
  ["v%"]  = {"0", "4", "5", "e"}, -- CYRILLIC SMALL LETTER SHORT U
  ["dz"]  = {"0", "4", "5", "f"}, -- CYRILLIC SMALL LETTER DZHE
  ["Y3"]  = {"0", "4", "6", "2"}, -- CYRILLIC CAPITAL LETTER YAT
  ["y3"]  = {"0", "4", "6", "3"}, -- CYRILLIC SMALL LETTER YAT
  ["O3"]  = {"0", "4", "6", "a"}, -- CYRILLIC CAPITAL LETTER BIG YUS
  ["o3"]  = {"0", "4", "6", "b"}, -- CYRILLIC SMALL LETTER BIG YUS
  ["F3"]  = {"0", "4", "7", "2"}, -- CYRILLIC CAPITAL LETTER FITA
  ["f3"]  = {"0", "4", "7", "3"}, -- CYRILLIC SMALL LETTER FITA
  ["V3"]  = {"0", "4", "7", "4"}, -- CYRILLIC CAPITAL LETTER IZHITSA
  ["v3"]  = {"0", "4", "7", "5"}, -- CYRILLIC SMALL LETTER IZHITSA
  ["C3"]  = {"0", "4", "8", "0"}, -- CYRILLIC CAPITAL LETTER KOPPA
  ["c3"]  = {"0", "4", "8", "1"}, -- CYRILLIC SMALL LETTER KOPPA
  ["G3"]  = {"0", "4", "9", "0"}, -- CYRILLIC CAPITAL LETTER GHE WITH UPTURN
  ["g3"]  = {"0", "4", "9", "1"}, -- CYRILLIC SMALL LETTER GHE WITH UPTURN
  ["A+"]  = {"0", "5", "d", "0"}, -- HEBREW LETTER ALEF
  ["B+"]  = {"0", "5", "d", "1"}, -- HEBREW LETTER BET
  ["G+"]  = {"0", "5", "d", "2"}, -- HEBREW LETTER GIMEL
  ["D+"]  = {"0", "5", "d", "3"}, -- HEBREW LETTER DALET
  ["H+"]  = {"0", "5", "d", "4"}, -- HEBREW LETTER HE
  ["W+"]  = {"0", "5", "d", "5"}, -- HEBREW LETTER VAV
  ["Z+"]  = {"0", "5", "d", "6"}, -- HEBREW LETTER ZAYIN
  ["X+"]  = {"0", "5", "d", "7"}, -- HEBREW LETTER HET
  ["Tj"]  = {"0", "5", "d", "8"}, -- HEBREW LETTER TET
  ["J+"]  = {"0", "5", "d", "9"}, -- HEBREW LETTER YOD
  ["K%"]  = {"0", "5", "d", "a"}, -- HEBREW LETTER FINAL KAF
  ["K+"]  = {"0", "5", "d", "b"}, -- HEBREW LETTER KAF
  ["L+"]  = {"0", "5", "d", "c"}, -- HEBREW LETTER LAMED
  ["M%"]  = {"0", "5", "d", "d"}, -- HEBREW LETTER FINAL MEM
  ["M+"]  = {"0", "5", "d", "e"}, -- HEBREW LETTER MEM
  ["N%"]  = {"0", "5", "d", "f"}, -- HEBREW LETTER FINAL NUN
  ["N+"]  = {"0", "5", "e", "0"}, -- HEBREW LETTER NUN
  ["S+"]  = {"0", "5", "e", "1"}, -- HEBREW LETTER SAMEKH
  ["E+"]  = {"0", "5", "e", "2"}, -- HEBREW LETTER AYIN
  ["P%"]  = {"0", "5", "e", "3"}, -- HEBREW LETTER FINAL PE
  ["P+"]  = {"0", "5", "e", "4"}, -- HEBREW LETTER PE
  ["Zj"]  = {"0", "5", "e", "5"}, -- HEBREW LETTER FINAL TSADI
  ["ZJ"]  = {"0", "5", "e", "6"}, -- HEBREW LETTER TSADI
  ["Q+"]  = {"0", "5", "e", "7"}, -- HEBREW LETTER QOF
  ["R+"]  = {"0", "5", "e", "8"}, -- HEBREW LETTER RESH
  ["Sh"]  = {"0", "5", "e", "9"}, -- HEBREW LETTER SHIN
  ["T+"]  = {"0", "5", "e", "a"}, -- HEBREW LETTER TAV
  [",+"]  = {"0", "6", "0", "c"}, -- ARABIC COMMA
  [";+"]  = {"0", "6", "1", "b"}, -- ARABIC SEMICOLON
  ["?+"]  = {"0", "6", "1", "f"}, -- ARABIC QUESTION MARK
  ["H'"]  = {"0", "6", "2", "1"}, -- ARABIC LETTER HAMZA
  ["aM"]  = {"0", "6", "2", "2"}, -- ARABIC LETTER ALEF WITH MADDA ABOVE
  ["aH"]  = {"0", "6", "2", "3"}, -- ARABIC LETTER ALEF WITH HAMZA ABOVE
  ["wH"]  = {"0", "6", "2", "4"}, -- ARABIC LETTER WAW WITH HAMZA ABOVE
  ["ah"]  = {"0", "6", "2", "5"}, -- ARABIC LETTER ALEF WITH HAMZA BELOW
  ["yH"]  = {"0", "6", "2", "6"}, -- ARABIC LETTER YEH WITH HAMZA ABOVE
  ["a+"]  = {"0", "6", "2", "7"}, -- ARABIC LETTER ALEF
  ["b+"]  = {"0", "6", "2", "8"}, -- ARABIC LETTER BEH
  ["tm"]  = {"0", "6", "2", "9"}, -- ARABIC LETTER TEH MARBUTA
  ["t+"]  = {"0", "6", "2", "a"}, -- ARABIC LETTER TEH
  ["tk"]  = {"0", "6", "2", "b"}, -- ARABIC LETTER THEH
  ["g+"]  = {"0", "6", "2", "c"}, -- ARABIC LETTER JEEM
  ["hk"]  = {"0", "6", "2", "d"}, -- ARABIC LETTER HAH
  ["x+"]  = {"0", "6", "2", "e"}, -- ARABIC LETTER KHAH
  ["d+"]  = {"0", "6", "2", "f"}, -- ARABIC LETTER DAL
  ["dk"]  = {"0", "6", "3", "0"}, -- ARABIC LETTER THAL
  ["r+"]  = {"0", "6", "3", "1"}, -- ARABIC LETTER REH
  ["z+"]  = {"0", "6", "3", "2"}, -- ARABIC LETTER ZAIN
  ["s+"]  = {"0", "6", "3", "3"}, -- ARABIC LETTER SEEN
  ["sn"]  = {"0", "6", "3", "4"}, -- ARABIC LETTER SHEEN
  ["c+"]  = {"0", "6", "3", "5"}, -- ARABIC LETTER SAD
  ["dd"]  = {"0", "6", "3", "6"}, -- ARABIC LETTER DAD
  ["tj"]  = {"0", "6", "3", "7"}, -- ARABIC LETTER TAH
  ["zH"]  = {"0", "6", "3", "8"}, -- ARABIC LETTER ZAH
  ["e+"]  = {"0", "6", "3", "9"}, -- ARABIC LETTER AIN
  ["i+"]  = {"0", "6", "3", "a"}, -- ARABIC LETTER GHAIN
  ["++"]  = {"0", "6", "4", "0"}, -- ARABIC TATWEEL
  ["f+"]  = {"0", "6", "4", "1"}, -- ARABIC LETTER FEH
  ["q+"]  = {"0", "6", "4", "2"}, -- ARABIC LETTER QAF
  ["k+"]  = {"0", "6", "4", "3"}, -- ARABIC LETTER KAF
  ["l+"]  = {"0", "6", "4", "4"}, -- ARABIC LETTER LAM
  ["m+"]  = {"0", "6", "4", "5"}, -- ARABIC LETTER MEEM
  ["n+"]  = {"0", "6", "4", "6"}, -- ARABIC LETTER NOON
  ["h+"]  = {"0", "6", "4", "7"}, -- ARABIC LETTER HEH
  ["w+"]  = {"0", "6", "4", "8"}, -- ARABIC LETTER WAW
  ["j+"]  = {"0", "6", "4", "9"}, -- ARABIC LETTER ALEF MAKSURA
  ["y+"]  = {"0", "6", "4", "a"}, -- ARABIC LETTER YEH
  [":+"]  = {"0", "6", "4", "b"}, -- ARABIC FATHATAN
  ["\"+"] = {"0", "6", "4", "c"}, -- ARABIC DAMMATAN
  ["=+"]  = {"0", "6", "4", "d"}, -- ARABIC KASRATAN
  ["/+"]  = {"0", "6", "4", "e"}, -- ARABIC FATHA
  ["'+"]  = {"0", "6", "4", "f"}, -- ARABIC DAMMA
  ["1+"]  = {"0", "6", "5", "0"}, -- ARABIC KASRA
  ["3+"]  = {"0", "6", "5", "1"}, -- ARABIC SHADDA
  ["0+"]  = {"0", "6", "5", "2"}, -- ARABIC SUKUN
  ["aS"]  = {"0", "6", "7", "0"}, -- ARABIC LETTER SUPERSCRIPT ALEF
  ["p+"]  = {"0", "6", "7", "e"}, -- ARABIC LETTER PEH
  ["v+"]  = {"0", "6", "a", "4"}, -- ARABIC LETTER VEH
  ["gf"]  = {"0", "6", "a", "f"}, -- ARABIC LETTER GAF
  ["0a"]  = {"0", "6", "f", "0"}, -- EXTENDED ARABIC-INDIC DIGIT ZERO
  ["1a"]  = {"0", "6", "f", "1"}, -- EXTENDED ARABIC-INDIC DIGIT ONE
  ["2a"]  = {"0", "6", "f", "2"}, -- EXTENDED ARABIC-INDIC DIGIT TWO
  ["3a"]  = {"0", "6", "f", "3"}, -- EXTENDED ARABIC-INDIC DIGIT THREE
  ["4a"]  = {"0", "6", "f", "4"}, -- EXTENDED ARABIC-INDIC DIGIT FOUR
  ["5a"]  = {"0", "6", "f", "5"}, -- EXTENDED ARABIC-INDIC DIGIT FIVE
  ["6a"]  = {"0", "6", "f", "6"}, -- EXTENDED ARABIC-INDIC DIGIT SIX
  ["7a"]  = {"0", "6", "f", "7"}, -- EXTENDED ARABIC-INDIC DIGIT SEVEN
  ["8a"]  = {"0", "6", "f", "8"}, -- EXTENDED ARABIC-INDIC DIGIT EIGHT
  ["9a"]  = {"0", "6", "f", "9"}, -- EXTENDED ARABIC-INDIC DIGIT NINE
  ["B."]  = {"1", "e", "0", "2"}, -- LATIN CAPITAL LETTER B WITH DOT ABOVE
  ["b."]  = {"1", "e", "0", "3"}, -- LATIN SMALL LETTER B WITH DOT ABOVE
  ["B_"]  = {"1", "e", "0", "6"}, -- LATIN CAPITAL LETTER B WITH LINE BELOW
  ["b_"]  = {"1", "e", "0", "7"}, -- LATIN SMALL LETTER B WITH LINE BELOW
  ["D."]  = {"1", "e", "0", "a"}, -- LATIN CAPITAL LETTER D WITH DOT ABOVE
  ["d."]  = {"1", "e", "0", "b"}, -- LATIN SMALL LETTER D WITH DOT ABOVE
  ["D_"]  = {"1", "e", "0", "e"}, -- LATIN CAPITAL LETTER D WITH LINE BELOW
  ["d_"]  = {"1", "e", "0", "f"}, -- LATIN SMALL LETTER D WITH LINE BELOW
  ["D,"]  = {"1", "e", "1", "0"}, -- LATIN CAPITAL LETTER D WITH CEDILLA
  ["d,"]  = {"1", "e", "1", "1"}, -- LATIN SMALL LETTER D WITH CEDILLA
  ["F."]  = {"1", "e", "1", "e"}, -- LATIN CAPITAL LETTER F WITH DOT ABOVE
  ["f."]  = {"1", "e", "1", "f"}, -- LATIN SMALL LETTER F WITH DOT ABOVE
  ["G-"]  = {"1", "e", "2", "0"}, -- LATIN CAPITAL LETTER G WITH MACRON
  ["g-"]  = {"1", "e", "2", "1"}, -- LATIN SMALL LETTER G WITH MACRON
  ["H."]  = {"1", "e", "2", "2"}, -- LATIN CAPITAL LETTER H WITH DOT ABOVE
  ["h."]  = {"1", "e", "2", "3"}, -- LATIN SMALL LETTER H WITH DOT ABOVE
  ["H:"]  = {"1", "e", "2", "6"}, -- LATIN CAPITAL LETTER H WITH DIAERESIS
  ["h:"]  = {"1", "e", "2", "7"}, -- LATIN SMALL LETTER H WITH DIAERESIS
  ["H,"]  = {"1", "e", "2", "8"}, -- LATIN CAPITAL LETTER H WITH CEDILLA
  ["h,"]  = {"1", "e", "2", "9"}, -- LATIN SMALL LETTER H WITH CEDILLA
  ["K'"]  = {"1", "e", "3", "0"}, -- LATIN CAPITAL LETTER K WITH ACUTE
  ["k'"]  = {"1", "e", "3", "1"}, -- LATIN SMALL LETTER K WITH ACUTE
  ["K_"]  = {"1", "e", "3", "4"}, -- LATIN CAPITAL LETTER K WITH LINE BELOW
  ["k_"]  = {"1", "e", "3", "5"}, -- LATIN SMALL LETTER K WITH LINE BELOW
  ["L_"]  = {"1", "e", "3", "a"}, -- LATIN CAPITAL LETTER L WITH LINE BELOW
  ["l_"]  = {"1", "e", "3", "b"}, -- LATIN SMALL LETTER L WITH LINE BELOW
  ["M'"]  = {"1", "e", "3", "e"}, -- LATIN CAPITAL LETTER M WITH ACUTE
  ["m'"]  = {"1", "e", "3", "f"}, -- LATIN SMALL LETTER M WITH ACUTE
  ["M."]  = {"1", "e", "4", "0"}, -- LATIN CAPITAL LETTER M WITH DOT ABOVE
  ["m."]  = {"1", "e", "4", "1"}, -- LATIN SMALL LETTER M WITH DOT ABOVE
  ["N."]  = {"1", "e", "4", "4"}, -- LATIN CAPITAL LETTER N WITH DOT ABOVE
  ["n."]  = {"1", "e", "4", "5"}, -- LATIN SMALL LETTER N WITH DOT ABOVE
  ["N_"]  = {"1", "e", "4", "8"}, -- LATIN CAPITAL LETTER N WITH LINE BELOW
  ["n_"]  = {"1", "e", "4", "9"}, -- LATIN SMALL LETTER N WITH LINE BELOW
  ["P'"]  = {"1", "e", "5", "4"}, -- LATIN CAPITAL LETTER P WITH ACUTE
  ["p'"]  = {"1", "e", "5", "5"}, -- LATIN SMALL LETTER P WITH ACUTE
  ["P."]  = {"1", "e", "5", "6"}, -- LATIN CAPITAL LETTER P WITH DOT ABOVE
  ["p."]  = {"1", "e", "5", "7"}, -- LATIN SMALL LETTER P WITH DOT ABOVE
  ["R."]  = {"1", "e", "5", "8"}, -- LATIN CAPITAL LETTER R WITH DOT ABOVE
  ["r."]  = {"1", "e", "5", "9"}, -- LATIN SMALL LETTER R WITH DOT ABOVE
  ["R_"]  = {"1", "e", "5", "e"}, -- LATIN CAPITAL LETTER R WITH LINE BELOW
  ["r_"]  = {"1", "e", "5", "f"}, -- LATIN SMALL LETTER R WITH LINE BELOW
  ["S."]  = {"1", "e", "6", "0"}, -- LATIN CAPITAL LETTER S WITH DOT ABOVE
  ["s."]  = {"1", "e", "6", "1"}, -- LATIN SMALL LETTER S WITH DOT ABOVE
  ["T."]  = {"1", "e", "6", "a"}, -- LATIN CAPITAL LETTER T WITH DOT ABOVE
  ["t."]  = {"1", "e", "6", "b"}, -- LATIN SMALL LETTER T WITH DOT ABOVE
  ["T_"]  = {"1", "e", "6", "e"}, -- LATIN CAPITAL LETTER T WITH LINE BELOW
  ["t_"]  = {"1", "e", "6", "f"}, -- LATIN SMALL LETTER T WITH LINE BELOW
  ["V?"]  = {"1", "e", "7", "c"}, -- LATIN CAPITAL LETTER V WITH TILDE
  ["v?"]  = {"1", "e", "7", "d"}, -- LATIN SMALL LETTER V WITH TILDE
  ["W!"]  = {"1", "e", "8", "0"}, -- LATIN CAPITAL LETTER W WITH GRAVE
  ["w!"]  = {"1", "e", "8", "1"}, -- LATIN SMALL LETTER W WITH GRAVE
  ["W'"]  = {"1", "e", "8", "2"}, -- LATIN CAPITAL LETTER W WITH ACUTE
  ["w'"]  = {"1", "e", "8", "3"}, -- LATIN SMALL LETTER W WITH ACUTE
  ["W:"]  = {"1", "e", "8", "4"}, -- LATIN CAPITAL LETTER W WITH DIAERESIS
  ["w:"]  = {"1", "e", "8", "5"}, -- LATIN SMALL LETTER W WITH DIAERESIS
  ["W."]  = {"1", "e", "8", "6"}, -- LATIN CAPITAL LETTER W WITH DOT ABOVE
  ["w."]  = {"1", "e", "8", "7"}, -- LATIN SMALL LETTER W WITH DOT ABOVE
  ["X."]  = {"1", "e", "8", "a"}, -- LATIN CAPITAL LETTER X WITH DOT ABOVE
  ["x."]  = {"1", "e", "8", "b"}, -- LATIN SMALL LETTER X WITH DOT ABOVE
  ["X:"]  = {"1", "e", "8", "c"}, -- LATIN CAPITAL LETTER X WITH DIAERESIS
  ["x:"]  = {"1", "e", "8", "d"}, -- LATIN SMALL LETTER X WITH DIAERESIS
  ["Y."]  = {"1", "e", "8", "e"}, -- LATIN CAPITAL LETTER Y WITH DOT ABOVE
  ["y."]  = {"1", "e", "8", "f"}, -- LATIN SMALL LETTER Y WITH DOT ABOVE
  ["Z>"]  = {"1", "e", "9", "0"}, -- LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
  ["z>"]  = {"1", "e", "9", "1"}, -- LATIN SMALL LETTER Z WITH CIRCUMFLEX
  ["Z_"]  = {"1", "e", "9", "4"}, -- LATIN CAPITAL LETTER Z WITH LINE BELOW
  ["z_"]  = {"1", "e", "9", "5"}, -- LATIN SMALL LETTER Z WITH LINE BELOW
  ["h_"]  = {"1", "e", "9", "6"}, -- LATIN SMALL LETTER H WITH LINE BELOW
  ["t:"]  = {"1", "e", "9", "7"}, -- LATIN SMALL LETTER T WITH DIAERESIS
  ["w0"]  = {"1", "e", "9", "8"}, -- LATIN SMALL LETTER W WITH RING ABOVE
  ["y0"]  = {"1", "e", "9", "9"}, -- LATIN SMALL LETTER Y WITH RING ABOVE
  ["A2"]  = {"1", "e", "a", "2"}, -- LATIN CAPITAL LETTER A WITH HOOK ABOVE
  ["a2"]  = {"1", "e", "a", "3"}, -- LATIN SMALL LETTER A WITH HOOK ABOVE
  ["E2"]  = {"1", "e", "b", "a"}, -- LATIN CAPITAL LETTER E WITH HOOK ABOVE
  ["e2"]  = {"1", "e", "b", "b"}, -- LATIN SMALL LETTER E WITH HOOK ABOVE
  ["E?"]  = {"1", "e", "b", "c"}, -- LATIN CAPITAL LETTER E WITH TILDE
  ["e?"]  = {"1", "e", "b", "d"}, -- LATIN SMALL LETTER E WITH TILDE
  ["I2"]  = {"1", "e", "c", "8"}, -- LATIN CAPITAL LETTER I WITH HOOK ABOVE
  ["i2"]  = {"1", "e", "c", "9"}, -- LATIN SMALL LETTER I WITH HOOK ABOVE
  ["O2"]  = {"1", "e", "c", "e"}, -- LATIN CAPITAL LETTER O WITH HOOK ABOVE
  ["o2"]  = {"1", "e", "c", "f"}, -- LATIN SMALL LETTER O WITH HOOK ABOVE
  ["U2"]  = {"1", "e", "e", "6"}, -- LATIN CAPITAL LETTER U WITH HOOK ABOVE
  ["u2"]  = {"1", "e", "e", "7"}, -- LATIN SMALL LETTER U WITH HOOK ABOVE
  ["Y!"]  = {"1", "e", "f", "2"}, -- LATIN CAPITAL LETTER Y WITH GRAVE
  ["y!"]  = {"1", "e", "f", "3"}, -- LATIN SMALL LETTER Y WITH GRAVE
  ["Y2"]  = {"1", "e", "f", "6"}, -- LATIN CAPITAL LETTER Y WITH HOOK ABOVE
  ["y2"]  = {"1", "e", "f", "7"}, -- LATIN SMALL LETTER Y WITH HOOK ABOVE
  ["Y?"]  = {"1", "e", "f", "8"}, -- LATIN CAPITAL LETTER Y WITH TILDE
  ["y?"]  = {"1", "e", "f", "9"}, -- LATIN SMALL LETTER Y WITH TILDE
  [";'"]  = {"1", "f", "0", "0"}, -- GREEK SMALL LETTER ALPHA WITH PSILI
  [",'"]  = {"1", "f", "0", "1"}, -- GREEK SMALL LETTER ALPHA WITH DASIA
  [";!"]  = {"1", "f", "0", "2"}, -- GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
  [",!"]  = {"1", "f", "0", "3"}, -- GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
  ["?;"]  = {"1", "f", "0", "4"}, -- GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
  ["?,"]  = {"1", "f", "0", "5"}, -- GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
  ["!:"]  = {"1", "f", "0", "6"}, -- GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
  ["?:"]  = {"1", "f", "0", "7"}, -- GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
  ["1N"]  = {"2", "0", "0", "2"}, -- EN SPACE
  ["1M"]  = {"2", "0", "0", "3"}, -- EM SPACE
  ["3M"]  = {"2", "0", "0", "4"}, -- THREE-PER-EM SPACE
  ["4M"]  = {"2", "0", "0", "5"}, -- FOUR-PER-EM SPACE
  ["6M"]  = {"2", "0", "0", "6"}, -- SIX-PER-EM SPACE
  ["1T"]  = {"2", "0", "0", "9"}, -- THIN SPACE
  ["1H"]  = {"2", "0", "0", "a"}, -- HAIR SPACE
  ["-1"]  = {"2", "0", "1", "0"}, -- HYPHEN
  ["-N"]  = {"2", "0", "1", "3"}, -- EN DASH
  ["-M"]  = {"2", "0", "1", "4"}, -- EM DASH
  ["-3"]  = {"2", "0", "1", "5"}, -- HORIZONTAL BAR
  ["!2"]  = {"2", "0", "1", "6"}, -- DOUBLE VERTICAL LINE
  ["=2"]  = {"2", "0", "1", "7"}, -- DOUBLE LOW LINE
  ["'6"]  = {"2", "0", "1", "8"}, -- LEFT SINGLE QUOTATION MARK
  ["'9"]  = {"2", "0", "1", "9"}, -- RIGHT SINGLE QUOTATION MARK
  [".9"]  = {"2", "0", "1", "a"}, -- SINGLE LOW-9 QUOTATION MARK
  ["9'"]  = {"2", "0", "1", "b"}, -- SINGLE HIGH-REVERSED-9 QUOTATION MARK
  ["\"6"] = {"2", "0", "1", "c"}, -- LEFT DOUBLE QUOTATION MARK
  ["\"9"] = {"2", "0", "1", "d"}, -- RIGHT DOUBLE QUOTATION MARK
  [":9"]  = {"2", "0", "1", "e"}, -- DOUBLE LOW-9 QUOTATION MARK
  ["9\""] = {"2", "0", "1", "f"}, -- DOUBLE HIGH-REVERSED-9 QUOTATION MARK
  ["/-"]  = {"2", "0", "2", "0"}, -- DAGGER
  ["/="]  = {"2", "0", "2", "1"}, -- DOUBLE DAGGER
  [".."]  = {"2", "0", "2", "5"}, -- TWO DOT LEADER
  ["%0"]  = {"2", "0", "3", "0"}, -- PER MILLE SIGN
  ["1'"]  = {"2", "0", "3", "2"}, -- PRIME
  ["2'"]  = {"2", "0", "3", "3"}, -- DOUBLE PRIME
  ["3'"]  = {"2", "0", "3", "4"}, -- TRIPLE PRIME
  ["1\""] = {"2", "0", "3", "5"}, -- REVERSED PRIME
  ["2\""] = {"2", "0", "3", "6"}, -- REVERSED DOUBLE PRIME
  ["3\""] = {"2", "0", "3", "7"}, -- REVERSED TRIPLE PRIME
  ["Ca"]  = {"2", "0", "3", "8"}, -- CARET
  ["<1"]  = {"2", "0", "3", "9"}, -- SINGLE LEFT-POINTING ANGLE QUOTATION MARK
  [">1"]  = {"2", "0", "3", "a"}, -- SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
  [":X"]  = {"2", "0", "3", "b"}, -- REFERENCE MARK
  ["'-"]  = {"2", "0", "3", "e"}, -- OVERLINE
  ["/f"]  = {"2", "0", "4", "4"}, -- FRACTION SLASH
  ["0S"]  = {"2", "0", "7", "0"}, -- SUPERSCRIPT ZERO
  ["4S"]  = {"2", "0", "7", "4"}, -- SUPERSCRIPT FOUR
  ["5S"]  = {"2", "0", "7", "5"}, -- SUPERSCRIPT FIVE
  ["6S"]  = {"2", "0", "7", "6"}, -- SUPERSCRIPT SIX
  ["7S"]  = {"2", "0", "7", "7"}, -- SUPERSCRIPT SEVEN
  ["8S"]  = {"2", "0", "7", "8"}, -- SUPERSCRIPT EIGHT
  ["9S"]  = {"2", "0", "7", "9"}, -- SUPERSCRIPT NINE
  ["+S"]  = {"2", "0", "7", "a"}, -- SUPERSCRIPT PLUS SIGN
  ["-S"]  = {"2", "0", "7", "b"}, -- SUPERSCRIPT MINUS
  ["=S"]  = {"2", "0", "7", "c"}, -- SUPERSCRIPT EQUALS SIGN
  ["(S"]  = {"2", "0", "7", "d"}, -- SUPERSCRIPT LEFT PARENTHESIS
  [")S"]  = {"2", "0", "7", "e"}, -- SUPERSCRIPT RIGHT PARENTHESIS
  ["nS"]  = {"2", "0", "7", "f"}, -- SUPERSCRIPT LATIN SMALL LETTER N
  ["0s"]  = {"2", "0", "8", "0"}, -- SUBSCRIPT ZERO
  ["1s"]  = {"2", "0", "8", "1"}, -- SUBSCRIPT ONE
  ["2s"]  = {"2", "0", "8", "2"}, -- SUBSCRIPT TWO
  ["3s"]  = {"2", "0", "8", "3"}, -- SUBSCRIPT THREE
  ["4s"]  = {"2", "0", "8", "4"}, -- SUBSCRIPT FOUR
  ["5s"]  = {"2", "0", "8", "5"}, -- SUBSCRIPT FIVE
  ["6s"]  = {"2", "0", "8", "6"}, -- SUBSCRIPT SIX
  ["7s"]  = {"2", "0", "8", "7"}, -- SUBSCRIPT SEVEN
  ["8s"]  = {"2", "0", "8", "8"}, -- SUBSCRIPT EIGHT
  ["9s"]  = {"2", "0", "8", "9"}, -- SUBSCRIPT NINE
  ["+s"]  = {"2", "0", "8", "a"}, -- SUBSCRIPT PLUS SIGN
  ["-s"]  = {"2", "0", "8", "b"}, -- SUBSCRIPT MINUS
  ["=s"]  = {"2", "0", "8", "c"}, -- SUBSCRIPT EQUALS SIGN
  ["(s"]  = {"2", "0", "8", "d"}, -- SUBSCRIPT LEFT PARENTHESIS
  [")s"]  = {"2", "0", "8", "e"}, -- SUBSCRIPT RIGHT PARENTHESIS
  ["Li"]  = {"2", "0", "a", "4"}, -- LIRA SIGN
  ["Pt"]  = {"2", "0", "a", "7"}, -- PESETA SIGN
  ["W="]  = {"2", "0", "a", "9"}, -- WON SIGN
  ["=e"]  = {"2", "0", "a", "c"}, -- EURO SIGN
  ["Eu"]  = {"2", "0", "a", "c"}, -- EURO SIGN
  ["=R"]  = {"2", "0", "b", "d"}, -- RUBLE SIGN
  ["=P"]  = {"2", "0", "b", "d"}, -- RUBLE SIGN
  ["oC"]  = {"2", "1", "0", "3"}, -- DEGREE CELSIUS
  ["co"]  = {"2", "1", "0", "5"}, -- CARE OF
  ["oF"]  = {"2", "1", "0", "9"}, -- DEGREE FAHRENHEIT
  ["N0"]  = {"2", "1", "1", "6"}, -- NUMERO SIGN
  ["PO"]  = {"2", "1", "1", "7"}, -- SOUND RECORDING COPYRIGHT
  ["Rx"]  = {"2", "1", "1", "e"}, -- PRESCRIPTION TAKE
  ["SM"]  = {"2", "1", "2", "0"}, -- SERVICE MARK
  ["TM"]  = {"2", "1", "2", "2"}, -- TRADE MARK SIGN
  ["Om"]  = {"2", "1", "2", "6"}, -- OHM SIGN
  ["AO"]  = {"2", "1", "2", "b"}, -- ANGSTROM SIGN
  ["13"]  = {"2", "1", "5", "3"}, -- VULGAR FRACTION ONE THIRD
  ["23"]  = {"2", "1", "5", "4"}, -- VULGAR FRACTION TWO THIRDS
  ["15"]  = {"2", "1", "5", "5"}, -- VULGAR FRACTION ONE FIFTH
  ["25"]  = {"2", "1", "5", "6"}, -- VULGAR FRACTION TWO FIFTHS
  ["35"]  = {"2", "1", "5", "7"}, -- VULGAR FRACTION THREE FIFTHS
  ["45"]  = {"2", "1", "5", "8"}, -- VULGAR FRACTION FOUR FIFTHS
  ["16"]  = {"2", "1", "5", "9"}, -- VULGAR FRACTION ONE SIXTH
  ["56"]  = {"2", "1", "5", "a"}, -- VULGAR FRACTION FIVE SIXTHS
  ["18"]  = {"2", "1", "5", "b"}, -- VULGAR FRACTION ONE EIGHTH
  ["38"]  = {"2", "1", "5", "c"}, -- VULGAR FRACTION THREE EIGHTHS
  ["58"]  = {"2", "1", "5", "d"}, -- VULGAR FRACTION FIVE EIGHTHS
  ["78"]  = {"2", "1", "5", "e"}, -- VULGAR FRACTION SEVEN EIGHTHS
  ["1R"]  = {"2", "1", "6", "0"}, -- ROMAN NUMERAL ONE
  ["2R"]  = {"2", "1", "6", "1"}, -- ROMAN NUMERAL TWO
  ["3R"]  = {"2", "1", "6", "2"}, -- ROMAN NUMERAL THREE
  ["4R"]  = {"2", "1", "6", "3"}, -- ROMAN NUMERAL FOUR
  ["5R"]  = {"2", "1", "6", "4"}, -- ROMAN NUMERAL FIVE
  ["6R"]  = {"2", "1", "6", "5"}, -- ROMAN NUMERAL SIX
  ["7R"]  = {"2", "1", "6", "6"}, -- ROMAN NUMERAL SEVEN
  ["8R"]  = {"2", "1", "6", "7"}, -- ROMAN NUMERAL EIGHT
  ["9R"]  = {"2", "1", "6", "8"}, -- ROMAN NUMERAL NINE
  ["aR"]  = {"2", "1", "6", "9"}, -- ROMAN NUMERAL TEN
  ["bR"]  = {"2", "1", "6", "a"}, -- ROMAN NUMERAL ELEVEN
  ["cR"]  = {"2", "1", "6", "b"}, -- ROMAN NUMERAL TWELVE
  ["1r"]  = {"2", "1", "7", "0"}, -- SMALL ROMAN NUMERAL ONE
  ["2r"]  = {"2", "1", "7", "1"}, -- SMALL ROMAN NUMERAL TWO
  ["3r"]  = {"2", "1", "7", "2"}, -- SMALL ROMAN NUMERAL THREE
  ["4r"]  = {"2", "1", "7", "3"}, -- SMALL ROMAN NUMERAL FOUR
  ["5r"]  = {"2", "1", "7", "4"}, -- SMALL ROMAN NUMERAL FIVE
  ["6r"]  = {"2", "1", "7", "5"}, -- SMALL ROMAN NUMERAL SIX
  ["7r"]  = {"2", "1", "7", "6"}, -- SMALL ROMAN NUMERAL SEVEN
  ["8r"]  = {"2", "1", "7", "7"}, -- SMALL ROMAN NUMERAL EIGHT
  ["9r"]  = {"2", "1", "7", "8"}, -- SMALL ROMAN NUMERAL NINE
  ["ar"]  = {"2", "1", "7", "9"}, -- SMALL ROMAN NUMERAL TEN
  ["br"]  = {"2", "1", "7", "a"}, -- SMALL ROMAN NUMERAL ELEVEN
  ["cr"]  = {"2", "1", "7", "b"}, -- SMALL ROMAN NUMERAL TWELVE
  ["<-"]  = {"2", "1", "9", "0"}, -- LEFTWARDS ARROW
  ["-!"]  = {"2", "1", "9", "1"}, -- UPWARDS ARROW
  ["->"]  = {"2", "1", "9", "2"}, -- RIGHTWARDS ARROW
  ["-v"]  = {"2", "1", "9", "3"}, -- DOWNWARDS ARROW
  ["<>"]  = {"2", "1", "9", "4"}, -- LEFT RIGHT ARROW
  ["UD"]  = {"2", "1", "9", "5"}, -- UP DOWN ARROW
  ["<="]  = {"2", "1", "d", "0"}, -- LEFTWARDS DOUBLE ARROW
  ["=>"]  = {"2", "1", "d", "2"}, -- RIGHTWARDS DOUBLE ARROW
  ["=="]  = {"2", "1", "d", "4"}, -- LEFT RIGHT DOUBLE ARROW
  ["FA"]  = {"2", "2", "0", "0"}, -- FOR ALL
  ["dP"]  = {"2", "2", "0", "2"}, -- PARTIAL DIFFERENTIAL
  ["TE"]  = {"2", "2", "0", "3"}, -- THERE EXISTS
  ["/0"]  = {"2", "2", "0", "5"}, -- EMPTY SET
  ["DE"]  = {"2", "2", "0", "6"}, -- INCREMENT
  ["NB"]  = {"2", "2", "0", "7"}, -- NABLA
  ["(-"]  = {"2", "2", "0", "8"}, -- ELEMENT OF
  ["-)"]  = {"2", "2", "0", "b"}, -- CONTAINS AS MEMBER
  ["*P"]  = {"2", "2", "0", "f"}, -- N-ARY PRODUCT
  ["+Z"]  = {"2", "2", "1", "1"}, -- N-ARY SUMMATION
  ["-2"]  = {"2", "2", "1", "2"}, -- MINUS SIGN
  ["-+"]  = {"2", "2", "1", "3"}, -- MINUS-OR-PLUS SIGN
  ["*-"]  = {"2", "2", "1", "7"}, -- ASTERISK OPERATOR
  ["Ob"]  = {"2", "2", "1", "8"}, -- RING OPERATOR
  ["Sb"]  = {"2", "2", "1", "9"}, -- BULLET OPERATOR
  ["RT"]  = {"2", "2", "1", "a"}, -- SQUARE ROOT
  ["0("]  = {"2", "2", "1", "d"}, -- PROPORTIONAL TO
  ["00"]  = {"2", "2", "1", "e"}, -- INFINITY
  ["-L"]  = {"2", "2", "1", "f"}, -- RIGHT ANGLE
  ["-V"]  = {"2", "2", "2", "0"}, -- ANGLE
  ["PP"]  = {"2", "2", "2", "5"}, -- PARALLEL TO
  ["AN"]  = {"2", "2", "2", "7"}, -- LOGICAL AND
  ["OR"]  = {"2", "2", "2", "8"}, -- LOGICAL OR
  ["(U"]  = {"2", "2", "2", "9"}, -- INTERSECTION
  [")U"]  = {"2", "2", "2", "a"}, -- UNION
  ["In"]  = {"2", "2", "2", "b"}, -- INTEGRAL
  ["DI"]  = {"2", "2", "2", "c"}, -- DOUBLE INTEGRAL
  ["Io"]  = {"2", "2", "2", "e"}, -- CONTOUR INTEGRAL
  [".:"]  = {"2", "2", "3", "4"}, -- THEREFORE
  [":."]  = {"2", "2", "3", "5"}, -- BECAUSE
  [":R"]  = {"2", "2", "3", "6"}, -- RATIO
  ["::"]  = {"2", "2", "3", "7"}, -- PROPORTION
  ["?1"]  = {"2", "2", "3", "c"}, -- TILDE OPERATOR
  ["CG"]  = {"2", "2", "3", "e"}, -- INVERTED LAZY S
  ["?-"]  = {"2", "2", "4", "3"}, -- ASYMPTOTICALLY EQUAL TO
  ["?="]  = {"2", "2", "4", "5"}, -- APPROXIMATELY EQUAL TO
  ["?2"]  = {"2", "2", "4", "8"}, -- ALMOST EQUAL TO
  ["=?"]  = {"2", "2", "4", "c"}, -- ALL EQUAL TO
  ["HI"]  = {"2", "2", "5", "3"}, -- IMAGE OF OR APPROXIMATELY EQUAL TO
  ["!="]  = {"2", "2", "6", "0"}, -- NOT EQUAL TO
  ["=3"]  = {"2", "2", "6", "1"}, -- IDENTICAL TO
  ["=<"]  = {"2", "2", "6", "4"}, -- LESS-THAN OR EQUAL TO
  [">="]  = {"2", "2", "6", "5"}, -- GREATER-THAN OR EQUAL TO
  ["<*"]  = {"2", "2", "6", "a"}, -- MUCH LESS-THAN
  ["*>"]  = {"2", "2", "6", "b"}, -- MUCH GREATER-THAN
  ["!<"]  = {"2", "2", "6", "e"}, -- NOT LESS-THAN
  ["!>"]  = {"2", "2", "6", "f"}, -- NOT GREATER-THAN
  ["(C"]  = {"2", "2", "8", "2"}, -- SUBSET OF
  [")C"]  = {"2", "2", "8", "3"}, -- SUPERSET OF
  ["(_"]  = {"2", "2", "8", "6"}, -- SUBSET OF OR EQUAL TO
  [")_"]  = {"2", "2", "8", "7"}, -- SUPERSET OF OR EQUAL TO
  ["0."]  = {"2", "2", "9", "9"}, -- CIRCLED DOT OPERATOR
  ["02"]  = {"2", "2", "9", "a"}, -- CIRCLED RING OPERATOR
  ["-T"]  = {"2", "2", "a", "5"}, -- UP TACK
  [".P"]  = {"2", "2", "c", "5"}, -- DOT OPERATOR
  [":3"]  = {"2", "2", "e", "e"}, -- VERTICAL ELLIPSIS
  [".3"]  = {"2", "2", "e", "f"}, -- MIDLINE HORIZONTAL ELLIPSIS
  ["Eh"]  = {"2", "3", "0", "2"}, -- HOUSE
  ["<7"]  = {"2", "3", "0", "8"}, -- LEFT CEILING
  [">7"]  = {"2", "3", "0", "9"}, -- RIGHT CEILING
  ["7<"]  = {"2", "3", "0", "a"}, -- LEFT FLOOR
  ["7>"]  = {"2", "3", "0", "b"}, -- RIGHT FLOOR
  ["NI"]  = {"2", "3", "1", "0"}, -- REVERSED NOT SIGN
  ["(A"]  = {"2", "3", "1", "2"}, -- ARC
  ["TR"]  = {"2", "3", "1", "5"}, -- TELEPHONE RECORDER
  ["Iu"]  = {"2", "3", "2", "0"}, -- TOP HALF INTEGRAL
  ["Il"]  = {"2", "3", "2", "1"}, -- BOTTOM HALF INTEGRAL
  ["</"]  = {"2", "3", "2", "9"}, -- LEFT-POINTING ANGLE BRACKET
  ["/>"]  = {"2", "3", "2", "a"}, -- RIGHT-POINTING ANGLE BRACKET
  ["Vs"]  = {"2", "4", "2", "3"}, -- OPEN BOX
  ["1h"]  = {"2", "4", "4", "0"}, -- OCR HOOK
  ["3h"]  = {"2", "4", "4", "1"}, -- OCR CHAIR
  ["2h"]  = {"2", "4", "4", "2"}, -- OCR FORK
  ["4h"]  = {"2", "4", "4", "3"}, -- OCR INVERTED FORK
  ["1j"]  = {"2", "4", "4", "6"}, -- OCR BRANCH BANK IDENTIFICATION
  ["2j"]  = {"2", "4", "4", "7"}, -- OCR AMOUNT OF CHECK
  ["3j"]  = {"2", "4", "4", "8"}, -- MICR ON US SYMBOL
  ["4j"]  = {"2", "4", "4", "9"}, -- MICR DASH SYMBOL
  ["1."]  = {"2", "4", "8", "8"}, -- DIGIT ONE FULL STOP
  ["2."]  = {"2", "4", "8", "9"}, -- DIGIT TWO FULL STOP
  ["3."]  = {"2", "4", "8", "a"}, -- DIGIT THREE FULL STOP
  ["4."]  = {"2", "4", "8", "b"}, -- DIGIT FOUR FULL STOP
  ["5."]  = {"2", "4", "8", "c"}, -- DIGIT FIVE FULL STOP
  ["6."]  = {"2", "4", "8", "d"}, -- DIGIT SIX FULL STOP
  ["7."]  = {"2", "4", "8", "e"}, -- DIGIT SEVEN FULL STOP
  ["8."]  = {"2", "4", "8", "f"}, -- DIGIT EIGHT FULL STOP
  ["9."]  = {"2", "4", "9", "0"}, -- DIGIT NINE FULL STOP
  ["hh"]  = {"2", "5", "0", "0"}, -- BOX DRAWINGS LIGHT HORIZONTAL
  ["HH"]  = {"2", "5", "0", "1"}, -- BOX DRAWINGS HEAVY HORIZONTAL
  ["vv"]  = {"2", "5", "0", "2"}, -- BOX DRAWINGS LIGHT VERTICAL
  ["VV"]  = {"2", "5", "0", "3"}, -- BOX DRAWINGS HEAVY VERTICAL
  ["3-"]  = {"2", "5", "0", "4"}, -- BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  ["3_"]  = {"2", "5", "0", "5"}, -- BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
  ["3!"]  = {"2", "5", "0", "6"}, -- BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
  ["3/"]  = {"2", "5", "0", "7"}, -- BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
  ["4-"]  = {"2", "5", "0", "8"}, -- BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
  ["4_"]  = {"2", "5", "0", "9"}, -- BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
  ["4!"]  = {"2", "5", "0", "a"}, -- BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
  ["4/"]  = {"2", "5", "0", "b"}, -- BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
  ["dr"]  = {"2", "5", "0", "c"}, -- BOX DRAWINGS LIGHT DOWN AND RIGHT
  ["dR"]  = {"2", "5", "0", "d"}, -- BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
  ["Dr"]  = {"2", "5", "0", "e"}, -- BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
  ["DR"]  = {"2", "5", "0", "f"}, -- BOX DRAWINGS HEAVY DOWN AND RIGHT
  ["dl"]  = {"2", "5", "1", "0"}, -- BOX DRAWINGS LIGHT DOWN AND LEFT
  ["dL"]  = {"2", "5", "1", "1"}, -- BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
  ["Dl"]  = {"2", "5", "1", "2"}, -- BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
  ["LD"]  = {"2", "5", "1", "3"}, -- BOX DRAWINGS HEAVY DOWN AND LEFT
  ["ur"]  = {"2", "5", "1", "4"}, -- BOX DRAWINGS LIGHT UP AND RIGHT
  ["uR"]  = {"2", "5", "1", "5"}, -- BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
  ["Ur"]  = {"2", "5", "1", "6"}, -- BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
  ["UR"]  = {"2", "5", "1", "7"}, -- BOX DRAWINGS HEAVY UP AND RIGHT
  ["ul"]  = {"2", "5", "1", "8"}, -- BOX DRAWINGS LIGHT UP AND LEFT
  ["uL"]  = {"2", "5", "1", "9"}, -- BOX DRAWINGS UP LIGHT AND LEFT HEAVY
  ["Ul"]  = {"2", "5", "1", "a"}, -- BOX DRAWINGS UP HEAVY AND LEFT LIGHT
  ["UL"]  = {"2", "5", "1", "b"}, -- BOX DRAWINGS HEAVY UP AND LEFT
  ["vr"]  = {"2", "5", "1", "c"}, -- BOX DRAWINGS LIGHT VERTICAL AND RIGHT
  ["vR"]  = {"2", "5", "1", "d"}, -- BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
  ["Vr"]  = {"2", "5", "2", "0"}, -- BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
  ["VR"]  = {"2", "5", "2", "3"}, -- BOX DRAWINGS HEAVY VERTICAL AND RIGHT
  ["vl"]  = {"2", "5", "2", "4"}, -- BOX DRAWINGS LIGHT VERTICAL AND LEFT
  ["vL"]  = {"2", "5", "2", "5"}, -- BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
  ["Vl"]  = {"2", "5", "2", "8"}, -- BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
  ["VL"]  = {"2", "5", "2", "b"}, -- BOX DRAWINGS HEAVY VERTICAL AND LEFT
  ["dh"]  = {"2", "5", "2", "c"}, -- BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
  ["dH"]  = {"2", "5", "2", "f"}, -- BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY
  ["Dh"]  = {"2", "5", "3", "0"}, -- BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
  ["DH"]  = {"2", "5", "3", "3"}, -- BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
  ["uh"]  = {"2", "5", "3", "4"}, -- BOX DRAWINGS LIGHT UP AND HORIZONTAL
  ["uH"]  = {"2", "5", "3", "7"}, -- BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
  ["Uh"]  = {"2", "5", "3", "8"}, -- BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
  ["UH"]  = {"2", "5", "3", "b"}, -- BOX DRAWINGS HEAVY UP AND HORIZONTAL
  ["vh"]  = {"2", "5", "3", "c"}, -- BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
  ["vH"]  = {"2", "5", "3", "f"}, -- BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY
  ["Vh"]  = {"2", "5", "4", "2"}, -- BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
  ["VH"]  = {"2", "5", "4", "b"}, -- BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  ["FD"]  = {"2", "5", "7", "1"}, -- BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
  ["BD"]  = {"2", "5", "7", "2"}, -- BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
  ["TB"]  = {"2", "5", "8", "0"}, -- UPPER HALF BLOCK
  ["LB"]  = {"2", "5", "8", "4"}, -- LOWER HALF BLOCK
  ["FB"]  = {"2", "5", "8", "8"}, -- FULL BLOCK
  ["lB"]  = {"2", "5", "8", "c"}, -- LEFT HALF BLOCK
  ["RB"]  = {"2", "5", "9", "0"}, -- RIGHT HALF BLOCK
  [".S"]  = {"2", "5", "9", "1"}, -- LIGHT SHADE
  [":S"]  = {"2", "5", "9", "2"}, -- MEDIUM SHADE
  ["?S"]  = {"2", "5", "9", "3"}, -- DARK SHADE
  ["fS"]  = {"2", "5", "a", "0"}, -- BLACK SQUARE
  ["OS"]  = {"2", "5", "a", "1"}, -- WHITE SQUARE
  ["RO"]  = {"2", "5", "a", "2"}, -- WHITE SQUARE WITH ROUNDED CORNERS
  ["Rr"]  = {"2", "5", "a", "3"}, -- WHITE SQUARE CONTAINING BLACK SMALL SQUARE
  ["RF"]  = {"2", "5", "a", "4"}, -- SQUARE WITH HORIZONTAL FILL
  ["RY"]  = {"2", "5", "a", "5"}, -- SQUARE WITH VERTICAL FILL
  ["RH"]  = {"2", "5", "a", "6"}, -- SQUARE WITH ORTHOGONAL CROSSHATCH FILL
  ["RZ"]  = {"2", "5", "a", "7"}, -- SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL
  ["RK"]  = {"2", "5", "a", "8"}, -- SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL
  ["RX"]  = {"2", "5", "a", "9"}, -- SQUARE WITH DIAGONAL CROSSHATCH FILL
  ["sB"]  = {"2", "5", "a", "a"}, -- BLACK SMALL SQUARE
  ["SR"]  = {"2", "5", "a", "c"}, -- BLACK RECTANGLE
  ["Or"]  = {"2", "5", "a", "d"}, -- WHITE RECTANGLE
  ["UT"]  = {"2", "5", "b", "2"}, -- BLACK UP-POINTING TRIANGLE
  ["uT"]  = {"2", "5", "b", "3"}, -- WHITE UP-POINTING TRIANGLE
  ["PR"]  = {"2", "5", "b", "6"}, -- BLACK RIGHT-POINTING TRIANGLE
  ["Tr"]  = {"2", "5", "b", "7"}, -- WHITE RIGHT-POINTING TRIANGLE
  ["Dt"]  = {"2", "5", "b", "c"}, -- BLACK DOWN-POINTING TRIANGLE
  ["dT"]  = {"2", "5", "b", "d"}, -- WHITE DOWN-POINTING TRIANGLE
  ["PL"]  = {"2", "5", "c", "0"}, -- BLACK LEFT-POINTING TRIANGLE
  ["Tl"]  = {"2", "5", "c", "1"}, -- WHITE LEFT-POINTING TRIANGLE
  ["Db"]  = {"2", "5", "c", "6"}, -- BLACK DIAMOND
  ["Dw"]  = {"2", "5", "c", "7"}, -- WHITE DIAMOND
  ["LZ"]  = {"2", "5", "c", "a"}, -- LOZENGE
  ["0m"]  = {"2", "5", "c", "b"}, -- WHITE CIRCLE
  ["0o"]  = {"2", "5", "c", "e"}, -- BULLSEYE
  ["0M"]  = {"2", "5", "c", "f"}, -- BLACK CIRCLE
  ["0L"]  = {"2", "5", "d", "0"}, -- CIRCLE WITH LEFT HALF BLACK
  ["0R"]  = {"2", "5", "d", "1"}, -- CIRCLE WITH RIGHT HALF BLACK
  ["Sn"]  = {"2", "5", "d", "8"}, -- INVERSE BULLET
  ["Ic"]  = {"2", "5", "d", "9"}, -- INVERSE WHITE CIRCLE
  ["Fd"]  = {"2", "5", "e", "2"}, -- BLACK LOWER RIGHT TRIANGLE
  ["Bd"]  = {"2", "5", "e", "3"}, -- BLACK LOWER LEFT TRIANGLE
  ["*2"]  = {"2", "6", "0", "5"}, -- BLACK STAR
  ["*1"]  = {"2", "6", "0", "6"}, -- WHITE STAR
  ["<H"]  = {"2", "6", "1", "c"}, -- WHITE LEFT POINTING INDEX
  [">H"]  = {"2", "6", "1", "e"}, -- WHITE RIGHT POINTING INDEX
  ["0u"]  = {"2", "6", "3", "a"}, -- WHITE SMILING FACE
  ["0U"]  = {"2", "6", "3", "b"}, -- BLACK SMILING FACE
  ["SU"]  = {"2", "6", "3", "c"}, -- WHITE SUN WITH RAYS
  ["Fm"]  = {"2", "6", "4", "0"}, -- FEMALE SIGN
  ["Ml"]  = {"2", "6", "4", "2"}, -- MALE SIGN
  ["cS"]  = {"2", "6", "6", "0"}, -- BLACK SPADE SUIT
  ["cH"]  = {"2", "6", "6", "1"}, -- WHITE HEART SUIT
  ["cD"]  = {"2", "6", "6", "2"}, -- WHITE DIAMOND SUIT
  ["cC"]  = {"2", "6", "6", "3"}, -- BLACK CLUB SUIT
  ["Md"]  = {"2", "6", "6", "9"}, -- QUARTER NOTE
  ["M8"]  = {"2", "6", "6", "a"}, -- EIGHTH NOTE
  ["M2"]  = {"2", "6", "6", "b"}, -- BEAMED EIGHTH NOTES
  ["Mb"]  = {"2", "6", "6", "d"}, -- MUSIC FLAT SIGN
  ["Mx"]  = {"2", "6", "6", "e"}, -- MUSIC NATURAL SIGN
  ["MX"]  = {"2", "6", "6", "f"}, -- MUSIC SHARP SIGN
  ["OK"]  = {"2", "7", "1", "3"}, -- CHECK MARK
  ["XX"]  = {"2", "7", "1", "7"}, -- BALLOT X
  ["-X"]  = {"2", "7", "2", "0"}, -- MALTESE CROSS
  ["IS"]  = {"3", "0", "0", "0"}, -- IDEOGRAPHIC SPACE
  [",_"]  = {"3", "0", "0", "1"}, -- IDEOGRAPHIC COMMA
  ["._"]  = {"3", "0", "0", "2"}, -- IDEOGRAPHIC FULL STOP
  ["+\""] = {"3", "0", "0", "3"}, -- DITTO MARK
  ["+_"]  = {"3", "0", "0", "4"}, -- JAPANESE INDUSTRIAL STANDARD SYMBOL
  ["*_"]  = {"3", "0", "0", "5"}, -- IDEOGRAPHIC ITERATION MARK
  [";_"]  = {"3", "0", "0", "6"}, -- IDEOGRAPHIC CLOSING MARK
  ["0_"]  = {"3", "0", "0", "7"}, -- IDEOGRAPHIC NUMBER ZERO
  ["<+"]  = {"3", "0", "0", "a"}, -- LEFT DOUBLE ANGLE BRACKET
  [">+"]  = {"3", "0", "0", "b"}, -- RIGHT DOUBLE ANGLE BRACKET
  ["<'"]  = {"3", "0", "0", "c"}, -- LEFT CORNER BRACKET
  [">'"]  = {"3", "0", "0", "d"}, -- RIGHT CORNER BRACKET
  ["<\""] = {"3", "0", "0", "e"}, -- LEFT WHITE CORNER BRACKET
  [">\""] = {"3", "0", "0", "f"}, -- RIGHT WHITE CORNER BRACKET
  ["(\""] = {"3", "0", "1", "0"}, -- LEFT BLACK LENTICULAR BRACKET
  [")\""] = {"3", "0", "1", "1"}, -- RIGHT BLACK LENTICULAR BRACKET
  ["=T"]  = {"3", "0", "1", "2"}, -- POSTAL MARK
  ["=_"]  = {"3", "0", "1", "3"}, -- GETA MARK
  ["('"]  = {"3", "0", "1", "4"}, -- LEFT TORTOISE SHELL BRACKET
  [")'"]  = {"3", "0", "1", "5"}, -- RIGHT TORTOISE SHELL BRACKET
  ["(I"]  = {"3", "0", "1", "6"}, -- LEFT WHITE LENTICULAR BRACKET
  [")I"]  = {"3", "0", "1", "7"}, -- RIGHT WHITE LENTICULAR BRACKET
  ["-?"]  = {"3", "0", "1", "c"}, -- WAVE DASH
  ["A5"]  = {"3", "0", "4", "1"}, -- HIRAGANA LETTER SMALL A
  ["a5"]  = {"3", "0", "4", "2"}, -- HIRAGANA LETTER A
  ["I5"]  = {"3", "0", "4", "3"}, -- HIRAGANA LETTER SMALL I
  ["i5"]  = {"3", "0", "4", "4"}, -- HIRAGANA LETTER I
  ["U5"]  = {"3", "0", "4", "5"}, -- HIRAGANA LETTER SMALL U
  ["u5"]  = {"3", "0", "4", "6"}, -- HIRAGANA LETTER U
  ["E5"]  = {"3", "0", "4", "7"}, -- HIRAGANA LETTER SMALL E
  ["e5"]  = {"3", "0", "4", "8"}, -- HIRAGANA LETTER E
  ["O5"]  = {"3", "0", "4", "9"}, -- HIRAGANA LETTER SMALL O
  ["o5"]  = {"3", "0", "4", "a"}, -- HIRAGANA LETTER O
  ["ka"]  = {"3", "0", "4", "b"}, -- HIRAGANA LETTER KA
  ["ga"]  = {"3", "0", "4", "c"}, -- HIRAGANA LETTER GA
  ["ki"]  = {"3", "0", "4", "d"}, -- HIRAGANA LETTER KI
  ["gi"]  = {"3", "0", "4", "e"}, -- HIRAGANA LETTER GI
  ["ku"]  = {"3", "0", "4", "f"}, -- HIRAGANA LETTER KU
  ["gu"]  = {"3", "0", "5", "0"}, -- HIRAGANA LETTER GU
  ["ke"]  = {"3", "0", "5", "1"}, -- HIRAGANA LETTER KE
  ["ge"]  = {"3", "0", "5", "2"}, -- HIRAGANA LETTER GE
  ["ko"]  = {"3", "0", "5", "3"}, -- HIRAGANA LETTER KO
  ["go"]  = {"3", "0", "5", "4"}, -- HIRAGANA LETTER GO
  ["sa"]  = {"3", "0", "5", "5"}, -- HIRAGANA LETTER SA
  ["za"]  = {"3", "0", "5", "6"}, -- HIRAGANA LETTER ZA
  ["si"]  = {"3", "0", "5", "7"}, -- HIRAGANA LETTER SI
  ["zi"]  = {"3", "0", "5", "8"}, -- HIRAGANA LETTER ZI
  ["su"]  = {"3", "0", "5", "9"}, -- HIRAGANA LETTER SU
  ["zu"]  = {"3", "0", "5", "a"}, -- HIRAGANA LETTER ZU
  ["se"]  = {"3", "0", "5", "b"}, -- HIRAGANA LETTER SE
  ["ze"]  = {"3", "0", "5", "c"}, -- HIRAGANA LETTER ZE
  ["so"]  = {"3", "0", "5", "d"}, -- HIRAGANA LETTER SO
  ["zo"]  = {"3", "0", "5", "e"}, -- HIRAGANA LETTER ZO
  ["ta"]  = {"3", "0", "5", "f"}, -- HIRAGANA LETTER TA
  ["da"]  = {"3", "0", "6", "0"}, -- HIRAGANA LETTER DA
  ["ti"]  = {"3", "0", "6", "1"}, -- HIRAGANA LETTER TI
  ["di"]  = {"3", "0", "6", "2"}, -- HIRAGANA LETTER DI
  ["tU"]  = {"3", "0", "6", "3"}, -- HIRAGANA LETTER SMALL TU
  ["tu"]  = {"3", "0", "6", "4"}, -- HIRAGANA LETTER TU
  ["du"]  = {"3", "0", "6", "5"}, -- HIRAGANA LETTER DU
  ["te"]  = {"3", "0", "6", "6"}, -- HIRAGANA LETTER TE
  ["de"]  = {"3", "0", "6", "7"}, -- HIRAGANA LETTER DE
  ["to"]  = {"3", "0", "6", "8"}, -- HIRAGANA LETTER TO
  ["do"]  = {"3", "0", "6", "9"}, -- HIRAGANA LETTER DO
  ["na"]  = {"3", "0", "6", "a"}, -- HIRAGANA LETTER NA
  ["ni"]  = {"3", "0", "6", "b"}, -- HIRAGANA LETTER NI
  ["nu"]  = {"3", "0", "6", "c"}, -- HIRAGANA LETTER NU
  ["ne"]  = {"3", "0", "6", "d"}, -- HIRAGANA LETTER NE
  ["no"]  = {"3", "0", "6", "e"}, -- HIRAGANA LETTER NO
  ["ha"]  = {"3", "0", "6", "f"}, -- HIRAGANA LETTER HA
  ["ba"]  = {"3", "0", "7", "0"}, -- HIRAGANA LETTER BA
  ["pa"]  = {"3", "0", "7", "1"}, -- HIRAGANA LETTER PA
  ["hi"]  = {"3", "0", "7", "2"}, -- HIRAGANA LETTER HI
  ["bi"]  = {"3", "0", "7", "3"}, -- HIRAGANA LETTER BI
  ["pi"]  = {"3", "0", "7", "4"}, -- HIRAGANA LETTER PI
  ["hu"]  = {"3", "0", "7", "5"}, -- HIRAGANA LETTER HU
  ["bu"]  = {"3", "0", "7", "6"}, -- HIRAGANA LETTER BU
  ["pu"]  = {"3", "0", "7", "7"}, -- HIRAGANA LETTER PU
  ["he"]  = {"3", "0", "7", "8"}, -- HIRAGANA LETTER HE
  ["be"]  = {"3", "0", "7", "9"}, -- HIRAGANA LETTER BE
  ["pe"]  = {"3", "0", "7", "a"}, -- HIRAGANA LETTER PE
  ["ho"]  = {"3", "0", "7", "b"}, -- HIRAGANA LETTER HO
  ["bo"]  = {"3", "0", "7", "c"}, -- HIRAGANA LETTER BO
  ["po"]  = {"3", "0", "7", "d"}, -- HIRAGANA LETTER PO
  ["ma"]  = {"3", "0", "7", "e"}, -- HIRAGANA LETTER MA
  ["mi"]  = {"3", "0", "7", "f"}, -- HIRAGANA LETTER MI
  ["mu"]  = {"3", "0", "8", "0"}, -- HIRAGANA LETTER MU
  ["me"]  = {"3", "0", "8", "1"}, -- HIRAGANA LETTER ME
  ["mo"]  = {"3", "0", "8", "2"}, -- HIRAGANA LETTER MO
  ["yA"]  = {"3", "0", "8", "3"}, -- HIRAGANA LETTER SMALL YA
  ["ya"]  = {"3", "0", "8", "4"}, -- HIRAGANA LETTER YA
  ["yU"]  = {"3", "0", "8", "5"}, -- HIRAGANA LETTER SMALL YU
  ["yu"]  = {"3", "0", "8", "6"}, -- HIRAGANA LETTER YU
  ["yO"]  = {"3", "0", "8", "7"}, -- HIRAGANA LETTER SMALL YO
  ["yo"]  = {"3", "0", "8", "8"}, -- HIRAGANA LETTER YO
  ["ra"]  = {"3", "0", "8", "9"}, -- HIRAGANA LETTER RA
  ["ri"]  = {"3", "0", "8", "a"}, -- HIRAGANA LETTER RI
  ["ru"]  = {"3", "0", "8", "b"}, -- HIRAGANA LETTER RU
  ["re"]  = {"3", "0", "8", "c"}, -- HIRAGANA LETTER RE
  ["ro"]  = {"3", "0", "8", "d"}, -- HIRAGANA LETTER RO
  ["wA"]  = {"3", "0", "8", "e"}, -- HIRAGANA LETTER SMALL WA
  ["wa"]  = {"3", "0", "8", "f"}, -- HIRAGANA LETTER WA
  ["wi"]  = {"3", "0", "9", "0"}, -- HIRAGANA LETTER WI
  ["we"]  = {"3", "0", "9", "1"}, -- HIRAGANA LETTER WE
  ["wo"]  = {"3", "0", "9", "2"}, -- HIRAGANA LETTER WO
  ["n5"]  = {"3", "0", "9", "3"}, -- HIRAGANA LETTER N
  ["vu"]  = {"3", "0", "9", "4"}, -- HIRAGANA LETTER VU
  ["\"5"] = {"3", "0", "9", "b"}, -- KATAKANA-HIRAGANA VOICED SOUND MARK
  ["05"]  = {"3", "0", "9", "c"}, -- KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  ["*5"]  = {"3", "0", "9", "d"}, -- HIRAGANA ITERATION MARK
  ["+5"]  = {"3", "0", "9", "e"}, -- HIRAGANA VOICED ITERATION MARK
  ["a6"]  = {"3", "0", "a", "1"}, -- KATAKANA LETTER SMALL A
  ["A6"]  = {"3", "0", "a", "2"}, -- KATAKANA LETTER A
  ["i6"]  = {"3", "0", "a", "3"}, -- KATAKANA LETTER SMALL I
  ["I6"]  = {"3", "0", "a", "4"}, -- KATAKANA LETTER I
  ["u6"]  = {"3", "0", "a", "5"}, -- KATAKANA LETTER SMALL U
  ["U6"]  = {"3", "0", "a", "6"}, -- KATAKANA LETTER U
  ["e6"]  = {"3", "0", "a", "7"}, -- KATAKANA LETTER SMALL E
  ["E6"]  = {"3", "0", "a", "8"}, -- KATAKANA LETTER E
  ["o6"]  = {"3", "0", "a", "9"}, -- KATAKANA LETTER SMALL O
  ["O6"]  = {"3", "0", "a", "a"}, -- KATAKANA LETTER O
  ["Ka"]  = {"3", "0", "a", "b"}, -- KATAKANA LETTER KA
  ["Ga"]  = {"3", "0", "a", "c"}, -- KATAKANA LETTER GA
  ["Ki"]  = {"3", "0", "a", "d"}, -- KATAKANA LETTER KI
  ["Gi"]  = {"3", "0", "a", "e"}, -- KATAKANA LETTER GI
  ["Ku"]  = {"3", "0", "a", "f"}, -- KATAKANA LETTER KU
  ["Gu"]  = {"3", "0", "b", "0"}, -- KATAKANA LETTER GU
  ["Ke"]  = {"3", "0", "b", "1"}, -- KATAKANA LETTER KE
  ["Ge"]  = {"3", "0", "b", "2"}, -- KATAKANA LETTER GE
  ["Ko"]  = {"3", "0", "b", "3"}, -- KATAKANA LETTER KO
  ["Go"]  = {"3", "0", "b", "4"}, -- KATAKANA LETTER GO
  ["Sa"]  = {"3", "0", "b", "5"}, -- KATAKANA LETTER SA
  ["Za"]  = {"3", "0", "b", "6"}, -- KATAKANA LETTER ZA
  ["Si"]  = {"3", "0", "b", "7"}, -- KATAKANA LETTER SI
  ["Zi"]  = {"3", "0", "b", "8"}, -- KATAKANA LETTER ZI
  ["Su"]  = {"3", "0", "b", "9"}, -- KATAKANA LETTER SU
  ["Zu"]  = {"3", "0", "b", "a"}, -- KATAKANA LETTER ZU
  ["Se"]  = {"3", "0", "b", "b"}, -- KATAKANA LETTER SE
  ["Ze"]  = {"3", "0", "b", "c"}, -- KATAKANA LETTER ZE
  ["So"]  = {"3", "0", "b", "d"}, -- KATAKANA LETTER SO
  ["Zo"]  = {"3", "0", "b", "e"}, -- KATAKANA LETTER ZO
  ["Ta"]  = {"3", "0", "b", "f"}, -- KATAKANA LETTER TA
  ["Da"]  = {"3", "0", "c", "0"}, -- KATAKANA LETTER DA
  ["Ti"]  = {"3", "0", "c", "1"}, -- KATAKANA LETTER TI
  ["Di"]  = {"3", "0", "c", "2"}, -- KATAKANA LETTER DI
  ["TU"]  = {"3", "0", "c", "3"}, -- KATAKANA LETTER SMALL TU
  ["Tu"]  = {"3", "0", "c", "4"}, -- KATAKANA LETTER TU
  ["Du"]  = {"3", "0", "c", "5"}, -- KATAKANA LETTER DU
  ["Te"]  = {"3", "0", "c", "6"}, -- KATAKANA LETTER TE
  ["De"]  = {"3", "0", "c", "7"}, -- KATAKANA LETTER DE
  ["To"]  = {"3", "0", "c", "8"}, -- KATAKANA LETTER TO
  ["Do"]  = {"3", "0", "c", "9"}, -- KATAKANA LETTER DO
  ["Na"]  = {"3", "0", "c", "a"}, -- KATAKANA LETTER NA
  ["Ni"]  = {"3", "0", "c", "b"}, -- KATAKANA LETTER NI
  ["Nu"]  = {"3", "0", "c", "c"}, -- KATAKANA LETTER NU
  ["Ne"]  = {"3", "0", "c", "d"}, -- KATAKANA LETTER NE
  ["No"]  = {"3", "0", "c", "e"}, -- KATAKANA LETTER NO
  ["Ha"]  = {"3", "0", "c", "f"}, -- KATAKANA LETTER HA
  ["Ba"]  = {"3", "0", "d", "0"}, -- KATAKANA LETTER BA
  ["Pa"]  = {"3", "0", "d", "1"}, -- KATAKANA LETTER PA
  ["Hi"]  = {"3", "0", "d", "2"}, -- KATAKANA LETTER HI
  ["Bi"]  = {"3", "0", "d", "3"}, -- KATAKANA LETTER BI
  ["Pi"]  = {"3", "0", "d", "4"}, -- KATAKANA LETTER PI
  ["Hu"]  = {"3", "0", "d", "5"}, -- KATAKANA LETTER HU
  ["Bu"]  = {"3", "0", "d", "6"}, -- KATAKANA LETTER BU
  ["Pu"]  = {"3", "0", "d", "7"}, -- KATAKANA LETTER PU
  ["He"]  = {"3", "0", "d", "8"}, -- KATAKANA LETTER HE
  ["Be"]  = {"3", "0", "d", "9"}, -- KATAKANA LETTER BE
  ["Pe"]  = {"3", "0", "d", "a"}, -- KATAKANA LETTER PE
  ["Ho"]  = {"3", "0", "d", "b"}, -- KATAKANA LETTER HO
  ["Bo"]  = {"3", "0", "d", "c"}, -- KATAKANA LETTER BO
  ["Po"]  = {"3", "0", "d", "d"}, -- KATAKANA LETTER PO
  ["Ma"]  = {"3", "0", "d", "e"}, -- KATAKANA LETTER MA
  ["Mi"]  = {"3", "0", "d", "f"}, -- KATAKANA LETTER MI
  ["Mu"]  = {"3", "0", "e", "0"}, -- KATAKANA LETTER MU
  ["Me"]  = {"3", "0", "e", "1"}, -- KATAKANA LETTER ME
  ["Mo"]  = {"3", "0", "e", "2"}, -- KATAKANA LETTER MO
  ["YA"]  = {"3", "0", "e", "3"}, -- KATAKANA LETTER SMALL YA
  ["Ya"]  = {"3", "0", "e", "4"}, -- KATAKANA LETTER YA
  ["YU"]  = {"3", "0", "e", "5"}, -- KATAKANA LETTER SMALL YU
  ["Yu"]  = {"3", "0", "e", "6"}, -- KATAKANA LETTER YU
  ["YO"]  = {"3", "0", "e", "7"}, -- KATAKANA LETTER SMALL YO
  ["Yo"]  = {"3", "0", "e", "8"}, -- KATAKANA LETTER YO
  ["Ra"]  = {"3", "0", "e", "9"}, -- KATAKANA LETTER RA
  ["Ri"]  = {"3", "0", "e", "a"}, -- KATAKANA LETTER RI
  ["Ru"]  = {"3", "0", "e", "b"}, -- KATAKANA LETTER RU
  ["Re"]  = {"3", "0", "e", "c"}, -- KATAKANA LETTER RE
  ["Ro"]  = {"3", "0", "e", "d"}, -- KATAKANA LETTER RO
  ["WA"]  = {"3", "0", "e", "e"}, -- KATAKANA LETTER SMALL WA
  ["Wa"]  = {"3", "0", "e", "f"}, -- KATAKANA LETTER WA
  ["Wi"]  = {"3", "0", "f", "0"}, -- KATAKANA LETTER WI
  ["We"]  = {"3", "0", "f", "1"}, -- KATAKANA LETTER WE
  ["Wo"]  = {"3", "0", "f", "2"}, -- KATAKANA LETTER WO
  ["N6"]  = {"3", "0", "f", "3"}, -- KATAKANA LETTER N
  ["Vu"]  = {"3", "0", "f", "4"}, -- KATAKANA LETTER VU
  ["KA"]  = {"3", "0", "f", "5"}, -- KATAKANA LETTER SMALL KA
  ["KE"]  = {"3", "0", "f", "6"}, -- KATAKANA LETTER SMALL KE
  ["Va"]  = {"3", "0", "f", "7"}, -- KATAKANA LETTER VA
  ["Vi"]  = {"3", "0", "f", "8"}, -- KATAKANA LETTER VI
  ["Ve"]  = {"3", "0", "f", "9"}, -- KATAKANA LETTER VE
  ["Vo"]  = {"3", "0", "f", "a"}, -- KATAKANA LETTER VO
  [".6"]  = {"3", "0", "f", "b"}, -- KATAKANA MIDDLE DOT
  ["-6"]  = {"3", "0", "f", "c"}, -- KATAKANA-HIRAGANA PROLONGED SOUND MARK
  ["*6"]  = {"3", "0", "f", "d"}, -- KATAKANA ITERATION MARK
  ["+6"]  = {"3", "0", "f", "e"}, -- KATAKANA VOICED ITERATION MARK
  ["b4"]  = {"3", "1", "0", "5"}, -- BOPOMOFO LETTER B
  ["p4"]  = {"3", "1", "0", "6"}, -- BOPOMOFO LETTER P
  ["m4"]  = {"3", "1", "0", "7"}, -- BOPOMOFO LETTER M
  ["f4"]  = {"3", "1", "0", "8"}, -- BOPOMOFO LETTER F
  ["d4"]  = {"3", "1", "0", "9"}, -- BOPOMOFO LETTER D
  ["t4"]  = {"3", "1", "0", "a"}, -- BOPOMOFO LETTER T
  ["n4"]  = {"3", "1", "0", "b"}, -- BOPOMOFO LETTER N
  ["l4"]  = {"3", "1", "0", "c"}, -- BOPOMOFO LETTER L
  ["g4"]  = {"3", "1", "0", "d"}, -- BOPOMOFO LETTER G
  ["k4"]  = {"3", "1", "0", "e"}, -- BOPOMOFO LETTER K
  ["h4"]  = {"3", "1", "0", "f"}, -- BOPOMOFO LETTER H
  ["j4"]  = {"3", "1", "1", "0"}, -- BOPOMOFO LETTER J
  ["q4"]  = {"3", "1", "1", "1"}, -- BOPOMOFO LETTER Q
  ["x4"]  = {"3", "1", "1", "2"}, -- BOPOMOFO LETTER X
  ["zh"]  = {"3", "1", "1", "3"}, -- BOPOMOFO LETTER ZH
  ["ch"]  = {"3", "1", "1", "4"}, -- BOPOMOFO LETTER CH
  ["sh"]  = {"3", "1", "1", "5"}, -- BOPOMOFO LETTER SH
  ["r4"]  = {"3", "1", "1", "6"}, -- BOPOMOFO LETTER R
  ["z4"]  = {"3", "1", "1", "7"}, -- BOPOMOFO LETTER Z
  ["c4"]  = {"3", "1", "1", "8"}, -- BOPOMOFO LETTER C
  ["s4"]  = {"3", "1", "1", "9"}, -- BOPOMOFO LETTER S
  ["a4"]  = {"3", "1", "1", "a"}, -- BOPOMOFO LETTER A
  ["o4"]  = {"3", "1", "1", "b"}, -- BOPOMOFO LETTER O
  ["e4"]  = {"3", "1", "1", "c"}, -- BOPOMOFO LETTER E
  ["ai"]  = {"3", "1", "1", "e"}, -- BOPOMOFO LETTER AI
  ["ei"]  = {"3", "1", "1", "f"}, -- BOPOMOFO LETTER EI
  ["au"]  = {"3", "1", "2", "0"}, -- BOPOMOFO LETTER AU
  ["ou"]  = {"3", "1", "2", "1"}, -- BOPOMOFO LETTER OU
  ["an"]  = {"3", "1", "2", "2"}, -- BOPOMOFO LETTER AN
  ["en"]  = {"3", "1", "2", "3"}, -- BOPOMOFO LETTER EN
  ["aN"]  = {"3", "1", "2", "4"}, -- BOPOMOFO LETTER ANG
  ["eN"]  = {"3", "1", "2", "5"}, -- BOPOMOFO LETTER ENG
  ["er"]  = {"3", "1", "2", "6"}, -- BOPOMOFO LETTER ER
  ["i4"]  = {"3", "1", "2", "7"}, -- BOPOMOFO LETTER I
  ["u4"]  = {"3", "1", "2", "8"}, -- BOPOMOFO LETTER U
  ["iu"]  = {"3", "1", "2", "9"}, -- BOPOMOFO LETTER IU
  ["v4"]  = {"3", "1", "2", "a"}, -- BOPOMOFO LETTER V
  ["nG"]  = {"3", "1", "2", "b"}, -- BOPOMOFO LETTER NG
  ["gn"]  = {"3", "1", "2", "c"}, -- BOPOMOFO LETTER GN
  ["1c"]  = {"3", "2", "2", "0"}, -- PARENTHESIZED IDEOGRAPH ONE
  ["2c"]  = {"3", "2", "2", "1"}, -- PARENTHESIZED IDEOGRAPH TWO
  ["3c"]  = {"3", "2", "2", "2"}, -- PARENTHESIZED IDEOGRAPH THREE
  ["4c"]  = {"3", "2", "2", "3"}, -- PARENTHESIZED IDEOGRAPH FOUR
  ["5c"]  = {"3", "2", "2", "4"}, -- PARENTHESIZED IDEOGRAPH FIVE
  ["6c"]  = {"3", "2", "2", "5"}, -- PARENTHESIZED IDEOGRAPH SIX
  ["7c"]  = {"3", "2", "2", "6"}, -- PARENTHESIZED IDEOGRAPH SEVEN
  ["8c"]  = {"3", "2", "2", "7"}, -- PARENTHESIZED IDEOGRAPH EIGHT
  ["9c"]  = {"3", "2", "2", "8"}, -- PARENTHESIZED IDEOGRAPH NINE
  ["ff"]  = {"f", "b", "0", "0"}, -- LATIN SMALL LIGATURE FF
  ["fi"]  = {"f", "b", "0", "1"}, -- LATIN SMALL LIGATURE FI
  ["fl"]  = {"f", "b", "0", "2"}, -- LATIN SMALL LIGATURE FL
  ["ft"]  = {"f", "b", "0", "5"}, -- LATIN SMALL LIGATURE LONG S T
  ["st"]  = {"f", "b", "0", "6"}, -- LATIN SMALL LIGATURE ST
  ["~!"]  = {"0", "0", "a", "1"}, -- INVERTED EXCLAMATION MARK
  ["c|"]  = {"0", "0", "a", "2"}, -- CENT SIGN
  ["$$"]  = {"0", "0", "a", "3"}, -- POUND SIGN
  ["ox"]  = {"0", "0", "a", "4"}, -- CURRENCY SIGN
  ["Y-"]  = {"0", "0", "a", "5"}, -- YEN SIGN
  ["||"]  = {"0", "0", "a", "6"}, -- BROKEN BAR
  ["cO"]  = {"0", "0", "a", "9"}, -- COPYRIGHT SIGN
  ["-,"]  = {"0", "0", "a", "c"}, -- NOT SIGN
  ["-="]  = {"0", "0", "a", "f"}, -- MACRON
  ["~o"]  = {"0", "0", "b", "0"}, -- DEGREE SIGN
  ["22"]  = {"0", "0", "b", "2"}, -- SUPERSCRIPT TWO
  ["33"]  = {"0", "0", "b", "3"}, -- SUPERSCRIPT THREE
  ["pp"]  = {"0", "0", "b", "6"}, -- PILCROW SIGN
  ["~."]  = {"0", "0", "b", "7"}, -- MIDDLE DOT
  ["11"]  = {"0", "0", "b", "9"}, -- SUPERSCRIPT ONE
  ["~?"]  = {"0", "0", "b", "f"}, -- INVERTED QUESTION MARK
  ["A`"]  = {"0", "0", "c", "0"}, -- LATIN CAPITAL LETTER A WITH GRAVE
  ["A^"]  = {"0", "0", "c", "2"}, -- LATIN CAPITAL LETTER A WITH CIRCUMFLEX
  ["A~"]  = {"0", "0", "c", "3"}, -- LATIN CAPITAL LETTER A WITH TILDE
  ["A\""] = {"0", "0", "c", "4"}, -- LATIN CAPITAL LETTER A WITH DIAERESIS
  ["A@"]  = {"0", "0", "c", "5"}, -- LATIN CAPITAL LETTER A WITH RING ABOVE
  ["E`"]  = {"0", "0", "c", "8"}, -- LATIN CAPITAL LETTER E WITH GRAVE
  ["E^"]  = {"0", "0", "c", "a"}, -- LATIN CAPITAL LETTER E WITH CIRCUMFLEX
  ["E\""] = {"0", "0", "c", "b"}, -- LATIN CAPITAL LETTER E WITH DIAERESIS
  ["I`"]  = {"0", "0", "c", "c"}, -- LATIN CAPITAL LETTER I WITH GRAVE
  ["I^"]  = {"0", "0", "c", "e"}, -- LATIN CAPITAL LETTER I WITH CIRCUMFLEX
  ["I\""] = {"0", "0", "c", "f"}, -- LATIN CAPITAL LETTER I WITH DIAERESIS
  ["N~"]  = {"0", "0", "d", "1"}, -- LATIN CAPITAL LETTER N WITH TILDE
  ["O`"]  = {"0", "0", "d", "2"}, -- LATIN CAPITAL LETTER O WITH GRAVE
  ["O^"]  = {"0", "0", "d", "4"}, -- LATIN CAPITAL LETTER O WITH CIRCUMFLEX
  ["O~"]  = {"0", "0", "d", "5"}, -- LATIN CAPITAL LETTER O WITH TILDE
  ["/\\"] = {"0", "0", "d", "7"}, -- MULTIPLICATION SIGN
  ["U`"]  = {"0", "0", "d", "9"}, -- LATIN CAPITAL LETTER U WITH GRAVE
  ["U^"]  = {"0", "0", "d", "b"}, -- LATIN CAPITAL LETTER U WITH CIRCUMFLEX
  ["Ip"]  = {"0", "0", "d", "e"}, -- LATIN CAPITAL LETTER THORN
  ["a`"]  = {"0", "0", "e", "0"}, -- LATIN SMALL LETTER A WITH GRAVE
  ["a^"]  = {"0", "0", "e", "2"}, -- LATIN SMALL LETTER A WITH CIRCUMFLEX
  ["a~"]  = {"0", "0", "e", "3"}, -- LATIN SMALL LETTER A WITH TILDE
  ["a\""] = {"0", "0", "e", "4"}, -- LATIN SMALL LETTER A WITH DIAERESIS
  ["a@"]  = {"0", "0", "e", "5"}, -- LATIN SMALL LETTER A WITH RING ABOVE
  ["e`"]  = {"0", "0", "e", "8"}, -- LATIN SMALL LETTER E WITH GRAVE
  ["e^"]  = {"0", "0", "e", "a"}, -- LATIN SMALL LETTER E WITH CIRCUMFLEX
  ["e\""] = {"0", "0", "e", "b"}, -- LATIN SMALL LETTER E WITH DIAERESIS
  ["i`"]  = {"0", "0", "e", "c"}, -- LATIN SMALL LETTER I WITH GRAVE
  ["i^"]  = {"0", "0", "e", "e"}, -- LATIN SMALL LETTER I WITH CIRCUMFLEX
  ["n~"]  = {"0", "0", "f", "1"}, -- LATIN SMALL LETTER N WITH TILDE
  ["o`"]  = {"0", "0", "f", "2"}, -- LATIN SMALL LETTER O WITH GRAVE
  ["o^"]  = {"0", "0", "f", "4"}, -- LATIN SMALL LETTER O WITH CIRCUMFLEX
  ["o~"]  = {"0", "0", "f", "5"}, -- LATIN SMALL LETTER O WITH TILDE
  ["u`"]  = {"0", "0", "f", "9"}, -- LATIN SMALL LETTER U WITH GRAVE
  ["u^"]  = {"0", "0", "f", "b"}, -- LATIN SMALL LETTER U WITH CIRCUMFLEX
  ["y\""] = {"0", "0", "f", "f"}, -- LATIN SMALL LETTER Y WITH DIAERESIS
  ["-^"]  = {"2", "1", "9", "1"}, -- UPWARDS ARROW
  ["''"]  = {"0", "3", "0", "1"}, -- COMBINING ACUTE ACCENT
}
